(function(){"use strict";var API=location.origin;var $=function(id){return document.getElementById(id);};var _esc=(typeof esc==="function")?esc:function(s){return String(s==null?"":s);};function _state(){try{return(typeof state!=="undefined")?state:null;}catch(e){return null;}}
function _sess(){try{return(typeof getCurSess==="function")?getCurSess():null;}catch(e){return null;}}
function _save(force){try{if(typeof saveSessions==="function")saveSessions(!!force);}catch(e){}}
function _fp(msg){try{return(typeof _msgFp==="function")?_msgFp(msg):"";}catch(e){return"";}}
function _toast(m){if(typeof toast==="function")toast(m);}
var AS={voices:[],options:{gender:[],age:[],dialect:[]},owner:"",filter:{gender:"",age:"",dialect:""},tagDraft:{gender:"",age:"",dialect:""},libPanel:null,itemMenu:null,playing:null,resultAudio:null,polls:{},elByMsg:new WeakMap(),inited:false,};window.AudioState=AS;var AUDIO_IDS=["upIconBtn","atChip","atSep","mediaSel","ustrip","audioLibSel","audioSpeedSel","audioRefSrcSel","modeSel","modelSel","arsec","styleSel","kfArea","upArea"];var HIDE_WHEN_AUDIO=["atChip","modeSel","modelSel","arsec","styleSel","kfArea","upArea"];var SHOW_WHEN_AUDIO=["upIconBtn","atSep","mediaSel","ustrip","audioLibSel","audioSpeedSel","audioRefSrcSel"];var _saved=null,_inAudio=false;function _capture(){if(_inAudio)return;_saved={};AUDIO_IDS.forEach(function(id){var e=$(id);_saved[id]=e?(e.style.display||""):"";});_inAudio=true;}
function _restore(){if(_saved)AUDIO_IDS.forEach(function(id){var e=$(id);if(e)e.style.display=_saved[id]||"";});_saved=null;_inAudio=false;}
function audioApplyMedia(){var st=_state();var isAudio=!!(st&&st.media==="audio");if(isAudio){_capture();HIDE_WHEN_AUDIO.forEach(function(id){var e=$(id);if(e)e.style.display="none";});SHOW_WHEN_AUDIO.forEach(function(id){var e=$(id);if(e)e.style.display="";});audioSyncRefSrcVisibility();if(typeof refreshSeg==="function"){refreshSeg("mediaSel");refreshSeg("audioSpeedSel");refreshSeg("audioRefSrcSel");}
var pEl=$("prompt");if(pEl)pEl.dataset.ph="输入要合成的文字，例如：您好，今天天气不错，一起去公园玩吧。";if(st)st.mode="reference";var fe=$("file");if(fe)fe.accept="audio/*";if(typeof syncEmpty==="function"){try{syncEmpty();}catch(e){}}
audioLoadVoices();return true;}
_restore();var fe2=$("file");if(fe2)fe2.accept="image/*,audio/*,video/*";return false;}
window.AudioLib={open:function(anchorBtn,onPick){var panel=audioBuildLibPanel();audioLoadVoices();audioRenderLib();panel.classList.add("show");positionPop(panel,anchorBtn);var closed=false;var close=function(){if(closed)return;closed=true;panel.classList.remove("show");document.removeEventListener("mousedown",onDocDown,true);if(onPick)document.removeEventListener("click",onDocClick,true);};var onDocDown=function(e){if(!e.target.closest(".alib-panel")&&!(anchorBtn&&e.target.closest("#"+anchorBtn.id)))close();};var onDocClick=function(e){var meta=e.target.closest(".alib-meta");if(meta&&meta.getAttribute("data-act")==="use"){e.stopPropagation();e.preventDefault();var item=meta.closest(".alib-item");var v=null;(AS.voices||[]).forEach(function(x){if(x.id===(item?item.dataset.id:null))v=x;});if(v&&onPick)onPick(v);close();}};setTimeout(function(){document.addEventListener("mousedown",onDocDown,true);if(onPick)document.addEventListener("click",onDocClick,true);},0);return close;}};window.audioApplyMedia=audioApplyMedia;var SPEED_MIN=0.25,SPEED_MAX=4.0,SPEED_STEP=0.25;function fmtSpeed(v){var n=Math.round(v*100)/100;return String(n)+"×";}
function audioSpeedOptions(){var out=[];for(var v=SPEED_MIN;v<=SPEED_MAX+1e-9;v=Math.round((v+SPEED_STEP)*100)/100){out.push({value:String(v),text:fmtSpeed(v)});}
return out;}
window.audioSpeedOptions=audioSpeedOptions;window.audioSetRefSrc=audioSetRefSrc;function audioInitSpeedSeg(){if(typeof fillSelectOptions!=="function"||typeof initSeg!=="function")return;fillSelectOptions("audioSpeed",audioSpeedOptions(),"1");initSeg("audioSpeedSel");if(typeof refreshSeg==="function")refreshSeg("audioSpeedSel");}
function audioSpeedValue(){var el=$("audioSpeed");return el&&el.value?el.value:"1";}
var REF_SRC_KEY="wb_tts_ref_src";var REF_SRC_ORIGINAL="original",REF_SRC_PREVIEW="preview";function audioRefSrcOptions(){return[{value:REF_SRC_ORIGINAL,text:"参考：原样本"},{value:REF_SRC_PREVIEW,text:"参考：转换后"},];}
function audioRefSrcValue(){try{if(localStorage.getItem(REF_SRC_KEY)===REF_SRC_PREVIEW)return REF_SRC_PREVIEW;}catch(e){}
return REF_SRC_ORIGINAL;}
function audioSetRefSrc(v){try{localStorage.setItem(REF_SRC_KEY,v===REF_SRC_PREVIEW?REF_SRC_PREVIEW:REF_SRC_ORIGINAL);}catch(e){}}
function audioInitRefSrcSeg(){if(typeof fillSelectOptions!=="function"||typeof initSeg!=="function")return;fillSelectOptions("audioRefSrc",audioRefSrcOptions(),audioRefSrcValue());initSeg("audioRefSrcSel");if(typeof refreshSeg==="function")refreshSeg("audioRefSrcSel");var sel=$("audioRefSrc");if(sel)sel.addEventListener("change",function(){audioSetRefSrc(sel.value);});}
function audioRefSrcLabel(v){return v===REF_SRC_PREVIEW?"转换后样本":"原样本";}
function audioSyncRefSrcVisibility(){var wrap=$("audioRefSrcSel");if(!wrap)return;if(!_inAudio)return;var st=_state();var hasLibVoice=!!(st&&(st.assets||[]).some(function(a){return a&&a.kind==="audio"&&a.voiceId;}));wrap.style.display=hasLibVoice?"":"none";}
function audioBuildLibPanel(){if(AS.libPanel)return AS.libPanel;var panel=document.createElement("div");panel.className="seg-pop alib-panel";panel.innerHTML='<div class="alib-hd">'+'<div class="alib-tabs">'+'<button type="button" class="alib-tab on" data-owner="">全部音色</button>'+'<button type="button" class="alib-tab" data-owner="mine">我的音色</button>'+'</div>'+'<span class="alib-count" id="alibCount"></span>'+'</div>'+'<div class="alib-filters">'+'<div class="alib-dd-slot" id="alibFGender"></div>'+'<div class="alib-dd-slot" id="alibFAge"></div>'+'<div class="alib-dd-slot" id="alibFDialect"></div>'+'</div>'+'<div class="alib-list" id="alibList"></div>'+'<div class="alib-ft">'+'<span class="alib-progress" id="alibProgress"></span>'+'<button type="button" class="alib-add" id="alibAdd">添加音色</button>'+'</div>';document.body.appendChild(panel);AS.libPanel=panel;panel.addEventListener("click",onLibClick);return panel;}
function audioWireLibSeg(){var wrap=$("audioLibSel");if(!wrap)return;var cur=wrap.querySelector(".seg-cur");if(!cur)return;var panel=audioBuildLibPanel();wrap._pop=panel;try{if(typeof segList!=="undefined"&&segList&&segList.indexOf(wrap)<0)segList.push(wrap);}catch(e){}
cur.addEventListener("click",function(e){e.stopPropagation();var isOpen=wrap.classList.contains("open");if(typeof closeAllSeg==="function")closeAllSeg();if(!isOpen){audioRenderLib();panel.classList.add("show");positionPop(panel,cur);wrap.classList.add("open");}});}
function positionPop(pop,curBtn){var r=curBtn.getBoundingClientRect();var gap=7,pad=8;var spaceAbove=r.top-gap-pad;var spaceBelow=window.innerHeight-r.bottom-gap-pad;var openUp=spaceAbove>=spaceBelow;var avail=openUp?spaceAbove:spaceBelow;pop.style.maxHeight=Math.max(160,avail)+"px";pop.style.top="";pop.style.bottom="";var pw=pop.offsetWidth||0;var left=r.left;var maxLeft=window.innerWidth-pw-pad;if(left>maxLeft)left=maxLeft;if(left<pad)left=pad;pop.style.left=left+"px";if(openUp)pop.style.bottom=(window.innerHeight-r.top+gap)+"px";else pop.style.top=(r.bottom+gap)+"px";pop.classList.toggle("alib-up",openUp);}
function ddHtml(axis,label,values,cur){var items=values.map(function(v){return'<div class="alib-dd-item'+(cur===v?' on':'')+'" data-axis="'+axis+'" data-val="'+_esc(v)+'">'+_esc(v)+'</div>';}).join("");if(!items)items='<div class="alib-dd-empty">暂无可选项</div>';return'<div class="alib-dd'+(cur?' on':'')+'" data-axis="'+axis+'">'+'<button type="button" class="alib-dd-cur"><span class="alib-dd-tx">'+_esc(cur?(label+"："+cur):label)+'</span><span class="seg-ar ic ic-chevron-down"></span></button>'+'<div class="alib-dd-pop">'+items+'</div></div>';}
function _renderFilter(slotId,axis,label,values,cur){var el=$(slotId);if(!el)return;el.innerHTML=ddHtml(axis,label,values,cur);}
function panelCloseAllDd(){closeItemMenu();if(!AS.libPanel)return;AS.libPanel.querySelectorAll(".alib-dd.open").forEach(function(x){x.classList.remove("open");});}
function _ddPosition(dd){if(!dd)return;dd.classList.remove("up");var pop=dd.querySelector(".alib-dd-pop");if(!pop)return;var list=AS.libPanel?AS.libPanel.querySelector(".alib-list"):null;var limitBottom=list?list.getBoundingClientRect().bottom:window.innerHeight;var r=dd.getBoundingClientRect();var ph=pop.offsetHeight||200;if(r.bottom+4+ph>limitBottom)dd.classList.add("up");}
function ensureItemMenu(){if(AS.itemMenu)return AS.itemMenu;var m=document.createElement("div");m.className="alib-menu";document.body.appendChild(m);m.addEventListener("click",onItemMenuClick);AS.itemMenu=m;return m;}
function closeItemMenu(){if(AS.itemMenu)AS.itemMenu.classList.remove("open");}
function openItemMenu(item,btn){var m=ensureItemMenu();var id=item.dataset.id;if(m.classList.contains("open")&&m.dataset.id===id){closeItemMenu();return;}
m.dataset.id=id;m.innerHTML='<div class="alib-dd-item" data-act="rename">重命名</div>'+'<div class="alib-dd-item" data-act="tags">标签</div>'+'<div class="alib-dd-item alib-dd-del" data-act="del">删除</div>';m.classList.add("open");var r=btn.getBoundingClientRect();var mw=m.offsetWidth||96,mh=m.offsetHeight||100;var left=Math.min(r.right-mw,window.innerWidth-mw-8);if(left<8)left=8;var top=r.bottom+4;if(top+mh>window.innerHeight-8)top=Math.max(8,r.top-mh-4);m.style.left=left+"px";m.style.top=top+"px";}
function onItemMenuClick(e){var it=e.target.closest(".alib-dd-item");if(!it)return;var m=AS.itemMenu;var id=m&&m.dataset.id;var act=it.dataset.act;var card=(AS.libPanel&&id)?AS.libPanel.querySelector('.alib-item[data-id="'+id+'"]'):null;closeItemMenu();if(act==="rename"&&card)libStartRename(card);else if(act==="tags"&&card)libToggleTags(card);else if(act==="del"&&id)libDelete(id);}
function audioRenderLib(){var panel=AS.libPanel;if(!panel)return;closeItemMenu();var o=AS.options||{};_renderFilter("alibFGender","gender","性别",o.gender||[],AS.filter.gender);_renderFilter("alibFAge","age","年龄",o.age||[],AS.filter.age);_renderFilter("alibFDialect","dialect","方言",o.dialect||[],AS.filter.dialect);panel.querySelectorAll(".alib-tab").forEach(function(b){b.classList.toggle("on",(b.dataset.owner||"")===AS.owner);});var list=AS.voices.filter(function(v){if(AS.owner&&v.owner!==AS.owner)return false;if(AS.filter.gender&&v.gender!==AS.filter.gender)return false;if(AS.filter.age&&v.age!==AS.filter.age)return false;if(AS.filter.dialect&&v.dialect!==AS.filter.dialect)return false;return true;});var cnt=$("alibCount");if(cnt)cnt.textContent="共 "+list.length+" 个";var box=$("alibList");if(!box)return;if(!list.length){box.innerHTML='<div class="alib-empty">还没有音色。点右下角「添加音色」上传一段参考音频，系统会自动归档并生成试听样本。</div>';return;}
box.innerHTML=list.map(libItemHtml).join("");}
var PLAY_SVG='<svg viewBox="0 0 24 24" width="13" height="13" fill="currentColor" aria-hidden="true"><path d="M8 5.2 L18.4 12 L8 18.8 Z"/></svg>';var PAUSE_SVG='<svg viewBox="0 0 24 24" width="13" height="13" fill="currentColor" aria-hidden="true"><rect x="7" y="5.4" width="3.6" height="13.2" rx="1.1"/><rect x="13.4" y="5.4" width="3.6" height="13.2" rx="1.1"/></svg>';var EDIT_SVG='<svg viewBox="0 0 24 24" width="15" height="15" fill="currentColor" aria-hidden="true"><circle cx="12" cy="5.6" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="12" cy="18.4" r="1.5"/></svg>';function libItemHtml(v){var tags=[v.gender,v.age,v.dialect].filter(Boolean);var tagsHtml=tags.length?tags.map(function(t){return'<span class="alib-tag">'+_esc(t)+'</span>';}).join(""):'<span class="alib-tag alib-tag-none">未分类</span>';if(v.preview_pending){tagsHtml+='<span class="alib-tag alib-tag-none">样本生成中…</span>';}else if(v.preview_error){tagsHtml+='<span class="alib-tag alib-tag-none" title="'+_esc(v.preview_error)+'">样本未生成</span>';}
var badge=v.owner==="preset"?'<span class="alib-badge">预装</span>':'';return'<div class="alib-item" data-id="'+_esc(v.id)+'">'+'<button type="button" class="alib-play" data-act="play" title="播放试听"'+(v.preview_url?'':' disabled')+'>'+PLAY_SVG+'</button>'+'<div class="alib-meta" data-act="use" title="点击加入素材列队">'+'<div class="alib-name">'+_esc(v.name)+badge+'</div>'+'<div class="alib-tags">'+tagsHtml+'</div>'+'</div>'+'<button type="button" class="alib-edit" data-act="edit" title="编辑">'+EDIT_SVG+'</button>'+'<audio class="alib-audio" preload="none" src="'+_esc(v.preview_url||"")+'"></audio>'+'<div class="alib-tagedit" style="display:none"></div>'+'</div>';}
function onLibClick(e){if(e.target.closest(".alib-name-input"))return;var ddCur=e.target.closest(".alib-dd-cur");if(ddCur){var dd=ddCur.closest(".alib-dd");var wasOpen=dd.classList.contains("open");panelCloseAllDd();if(!wasOpen){dd.classList.add("open");_ddPosition(dd);}
return;}
var ddItem=e.target.closest(".alib-dd-item");if(ddItem&&ddItem.dataset.axis){var axis=ddItem.dataset.axis,val=ddItem.dataset.val;if(ddItem.closest(".alib-tagedit")){AS.tagDraft[axis]=(AS.tagDraft[axis]===val)?"":val;libRenderTagEdit(ddItem.closest(".alib-item"));}else{AS.filter[axis]=(AS.filter[axis]===val)?"":val;audioRenderLib();}
return;}
var editBtn=e.target.closest('[data-act="edit"]');if(editBtn){var itE=editBtn.closest(".alib-item");if(itE){if(AS.libPanel)AS.libPanel.querySelectorAll(".alib-dd.open").forEach(function(x){x.classList.remove("open");});openItemMenu(itE,editBtn);}
return;}
panelCloseAllDd();var tab=e.target.closest(".alib-tab");if(tab){AS.owner=tab.dataset.owner||"";audioRenderLib();return;}
if(e.target.closest("#alibAdd")){libAddVoice();return;}
if(e.target.closest('[data-act="tsave"]')){var it0=e.target.closest(".alib-item");if(it0)libSaveTags(it0);return;}
var item=e.target.closest(".alib-item");if(!item)return;var id=item.dataset.id;var actBtn=e.target.closest("[data-act]");var act=actBtn?actBtn.dataset.act:"";if(act==="play"){libPlay(item);return;}
if(act==="use"){libUse(id);return;}
if(act==="rename"){libStartRename(item);return;}
if(act==="tags"){libToggleTags(item);return;}
if(act==="del"){libDelete(id);return;}}
function _resetPlayIcon(item){var b=item&&item.querySelector(".alib-play");if(b)b.innerHTML=PLAY_SVG;}
function stopPreview(){if(AS.playing){try{AS.playing.pause();}catch(e){}AS.playing=null;}
document.querySelectorAll(".alib-item.playing").forEach(function(n){n.classList.remove("playing");_resetPlayIcon(n);});}
if(window.MediaStop){window.MediaStop.register(function(){try{stopPreview();}catch(e){}});}
function libPlay(item){var au=item.querySelector(".alib-audio");if(!au||!au.src)return;var btn=item.querySelector(".alib-play");if(AS.playing===au){au.pause();AS.playing=null;item.classList.remove("playing");if(btn)btn.innerHTML=PLAY_SVG;return;}
stopPreview();try{au.currentTime=0;}catch(e){}
au.play().catch(function(){});AS.playing=au;item.classList.add("playing");if(btn)btn.innerHTML=PAUSE_SVG;au.onended=function(){if(AS.playing===au){AS.playing=null;item.classList.remove("playing");if(btn)btn.innerHTML=PLAY_SVG;}};}
function _voiceById(id){return AS.voices.filter(function(v){return v.id===id;})[0];}
function _resyncPlaceholder(){var run=function(){if(typeof autoGrow==="function")autoGrow();if(typeof syncEmpty==="function"){try{syncEmpty();}catch(e){}}};run();try{requestAnimationFrame(run);}catch(e){}
setTimeout(run,160);}
function libUse(id){var v=_voiceById(id);if(!v)return;var st=_state();if(!st)return;var url=v.audio_url||v.preview_url||"";if(!url){_toast("该音色缺少音频文件");return;}
st.assets=(st.assets||[]).filter(function(a){return a.kind!=="audio";});st.assets.push({num:st.assets.length+1,url:url,kind:"audio",name:v.name,voiceId:v.id,uploading:false});if(typeof renumberAssets==="function")renumberAssets();if(typeof renderUstrip==="function")renderUstrip();_resyncPlaceholder();if(typeof closeAllSeg==="function")closeAllSeg();_toast("已加入素材列队："+v.name);}
async function libAddVoice(){if(typeof window.ttsPickAudio!=="function"){_toast("上传组件未加载");return;}
var f=await window.ttsPickAudio();if(!f)return;var btn=$("alibAdd"),prog=$("alibProgress");if(btn){btn.disabled=true;btn.textContent="归档中…";}
if(prog)prog.textContent="正在保存参考音频…";try{var r=await fetch(API+"/api/tts/voices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reference_audio:f.dataUrl,name:"",gender:"",age:"",dialect:""}),});var d=await r.json().catch(function(){return{error:"返回解析失败"};});if(!r.ok||d.error){_toast("添加失败："+(d.error||("HTTP "+r.status)));}
else{var v=d.voice||{};await audioLoadVoices();audioRenderLib();_toast("已归档「"+v.name+"」，试听样本生成中…");await libWaitPreview(v.id);}}catch(e){_toast("添加失败："+e.message);}
finally{if(btn){btn.disabled=false;btn.textContent="添加音色";}
if(prog)prog.textContent="";}}
function libWaitPreview(vid){var prog=$("alibProgress");var tries=0,MAX=20;return new Promise(function(resolve){function tick(){Promise.resolve(audioLoadVoices()).then(function(){var list=AS.voices||[],v=null;for(var i=0;i<list.length;i++){if(list[i].id===vid){v=list[i];break;}}
if(!v){resolve();return;}
if(v.has_preview){_toast("试听样本已生成，可点音色试听");resolve();return;}
if(v.preview_error){_toast("试听样本生成失败："+v.preview_error);resolve();return;}
if(++tries>=MAX){_toast("试听样本仍在生成中，稍后到音色库查看即可");resolve();return;}
if(prog)prog.textContent="试听样本生成中…（已等 "+tries*2+"s）";setTimeout(tick,2000);}).catch(function(){resolve();});}
tick();});}
function libStartRename(item){if(!item)return;var nameEl=item.querySelector(".alib-name");if(!nameEl||nameEl.querySelector(".alib-name-input"))return;var v=_voiceById(item.dataset.id)||{};var cur=v.name||"";var input=document.createElement("input");input.type="text";input.className="alib-name-input";input.value=cur;nameEl.innerHTML="";nameEl.appendChild(input);input.focus();try{input.select();}catch(e){}
var settled=false;function finish(save){if(settled)return;settled=true;var nv=(input.value||"").trim();if(!save||!nv||nv===cur){audioRenderLib();return;}
libRenameTo(item.dataset.id,nv);}
input.addEventListener("keydown",function(ev){if(ev.key==="Enter"){ev.preventDefault();finish(true);}
else if(ev.key==="Escape"){ev.preventDefault();finish(false);}});input.addEventListener("blur",function(){finish(true);});input.addEventListener("click",function(ev){ev.stopPropagation();});}
async function libRenameTo(id,name){try{var r=await fetch(API+"/api/tts/voices/"+encodeURIComponent(id),{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name}),});var d=await r.json().catch(function(){return{};});if(!r.ok||d.error){_toast("重命名失败："+(d.error||r.status));return;}
await audioLoadVoices();audioRenderLib();_toast("已重命名");}catch(e){_toast("重命名失败："+e.message);}}
async function libDelete(id){var v=_voiceById(id);if(!v)return;if(!confirm("确定删除音色「"+v.name+"」？它的参考音频可在资产库中查看。"))return;try{var r=await fetch(API+"/api/tts/voices/"+encodeURIComponent(id),{method:"DELETE"});var d=await r.json().catch(function(){return{};});if(!r.ok||d.error){_toast("删除失败："+(d.error||r.status));return;}
await audioLoadVoices();audioRenderLib();_toast("已删除");}catch(e){_toast("删除失败："+e.message);}}
function libToggleTags(item){var box=item.querySelector(".alib-tagedit");if(!box)return;if(box.style.display!=="none"){box.style.display="none";panelCloseAllDd();return;}
var v=_voiceById(item.dataset.id)||{};AS.tagDraft={gender:v.gender||"",age:v.age||"",dialect:v.dialect||""};libRenderTagEdit(item);box.style.display="";}
function libRenderTagEdit(item){if(!item)return;var box=item.querySelector(".alib-tagedit");if(!box)return;var o=AS.options||{};var d=AS.tagDraft||{gender:"",age:"",dialect:""};box.innerHTML=ddHtml("gender","性别",o.gender||[],d.gender)+
ddHtml("age","年龄",o.age||[],d.age)+
ddHtml("dialect","方言",o.dialect||[],d.dialect)+'<button type="button" class="alib-tsave" data-act="tsave">保存</button>';}
async function libSaveTags(item){var id=item.dataset.id;var d0=AS.tagDraft||{};var body={gender:d0.gender||"",age:d0.age||"",dialect:d0.dialect||""};try{var r=await fetch(API+"/api/tts/voices/"+encodeURIComponent(id),{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),});var d=await r.json().catch(function(){return{};});if(!r.ok||d.error){_toast("保存标签失败："+(d.error||r.status));return;}
await audioLoadVoices();audioRenderLib();_toast("标签已更新");}catch(e){_toast("保存标签失败："+e.message);}}
function audioLoadVoices(){return fetch(API+"/api/tts/voices").then(function(r){return r.json();}).then(function(d){AS.voices=(d&&d.voices)||[];AS.options=(d&&d.options)||{gender:[],age:[],dialect:[]};if(AS.libPanel&&AS.libPanel.classList.contains("show"))audioRenderLib();}).catch(function(){});}
function _am(msg){return(msg&&msg.audio)||{};}
function audioBuildSession(msg){var a=_am(msg);var stream=$("stream");var welcome=$("welcome");if(welcome)welcome.style.setProperty("display","none");var el=document.createElement("div");el.className="msg audio-sess bot";el._msgData=msg;el.innerHTML='<div class="bubble">'+'<div class="audio-user-line">'+
(a.refUrl?'<button type="button" class="ref-sq" data-refurl="'+_esc(a.refUrl)+'"'+' title="播放 / 暂停本次使用的参考音频">'+REF_PLAY_SVG+'</button>':'')+'<div class="audio-user-text">'+_esc(a.text||"")+'</div>'+'</div>'+'<div class="audio-user-chips">'+_chipsHtml(a)+'</div>'+'<div class="audio-out">'+'<div class="audio-cards"></div>'+'<div class="audio-out-foot">'+'<button class="uibtn audio-edit-btn" type="button"><span class="ic ic-reuse" aria-hidden="true"></span><span>返回编辑</span></button>'+'<button class="uibtn uibtn--del audio-del-btn" type="button"><span class="ic ic-del" aria-hidden="true"></span><span>删除</span></button>'+'<span class="audio-out-status"></span>'+'</div>'+'</div>'+'</div>';el.querySelector(".audio-edit-btn").addEventListener("click",function(){audioReturnEdit(a);});el.querySelector(".audio-del-btn").addEventListener("click",function(){audioDeleteMsg(msg,el);});var sq=el.querySelector(".ref-sq");if(sq)sq.addEventListener("click",function(){_toggleRefAudio(sq);});audioPaint(el,msg);if(stream){stream.appendChild(el);stream.scrollTop=stream.scrollHeight;}
AS.elByMsg.set(msg,el);return el;}
function _chipsHtml(a){var src=a.refSource?'<span class="mini"><b>参考来源</b> '+_esc(audioRefSrcLabel(a.refSource))+'</span>':'';return'<span class="mini"><b>音色</b> '+_esc(a.voiceName||"默认音色")+'</span>'
+'<span class="mini"><b>语速</b> '+_esc(fmtSpeed(Number(a.speed)||1))+'</span>'
+src;}
var REF_PLAY_SVG='<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M8 5.2 L18.6 12 L8 18.8 Z"/></svg>';var REF_PAUSE_SVG='<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="7" y="5" width="3.7" height="14" rx="1.2"/><rect x="13.3" y="5" width="3.7" height="14" rx="1.2"/></svg>';function _refBtnReset(btn){if(!btn)return;btn.classList.remove("on");btn.innerHTML=REF_PLAY_SVG;}
function _toggleRefAudio(btn){var u=btn.dataset.refurl;if(!u)return;var au=AS.refAudio;if(au&&au._refSrc!==u){try{au.pause();}catch(e){}
_refBtnReset(AS.refBtn);au=null;}
if(!au){try{au=new Audio(u);}catch(e){return;}
au._refSrc=u;au.addEventListener("ended",function(){_refBtnReset(btn);});AS.refAudio=au;AS.refBtn=btn;}
if(!au.paused){try{au.pause();}catch(e){}
_refBtnReset(btn);}else{au.play().catch(function(){});btn.classList.add("on");btn.innerHTML=REF_PAUSE_SVG;}}
function _pauseRefAudio(){var au=AS.refAudio;if(au&&!au.paused){try{au.pause();}catch(e){}}
_refBtnReset(AS.refBtn);}
function audioPaint(el,msg){if(!el)return;var a=_am(msg);var out=el.querySelector(".audio-out");var cards=el.querySelector(".audio-cards");var status=el.querySelector(".audio-out-status");if(!cards)return;var cands=a.candidates||[];var errs=a.errors||[];var total=Math.max(1,Number(a.count)||2);var done=(a.status!=="processing");if(done&&!cands.length){var m0=(errs[0]&&errs[0].message)||"生成失败";cards.innerHTML='<div class="audio-fail">生成失败：'+_esc(m0)+'<button class="uibtn audio-retry-btn" type="button">重试</button></div>';if(status)status.textContent="生成失败";var rb=cards.querySelector(".audio-retry-btn");if(rb)rb.addEventListener("click",function(){audioRetry(msg);});return;}
var html="";for(var i=0;i<total;i++){var c=null;for(var k=0;k<cands.length;k++){if(cands[k].index===i){c=cands[k];break;}}
if(c){if(!c.color)c.color=_acColor();html+=audioCardHtml(c,i);}else if(done){html+=audioErrorCardHtml(i,(errs[0]&&errs[0].message)||"未生成");}else{html+=audioPlaceholderHtml(i);}}
cards.innerHTML=html;audioWireCards(out);if(status){status.textContent=done?(cands.length?("已生成 "+cands.length+" 条"):"生成失败"):(cands.length?("生成中…（已完成 "+cands.length+" 条）"):"生成中…");}}
function audioSetFailed(msg,text){var a=_am(msg);a.status="failed";if(a.jobId&&AS.polls[a.jobId]){clearTimeout(AS.polls[a.jobId]);delete AS.polls[a.jobId];}
if(!(a.candidates||[]).length)a.errors=[{index:0,message:text}];msg.status="failed";audioPaint(AS.elByMsg.get(msg),msg);_save(false);}
function audioRetry(msg){var a=_am(msg);a.status="processing";a.jobId="";a.candidates=[];a.errors=[];msg.status="processing";audioPaint(AS.elByMsg.get(msg),msg);_save(false);audioRequest(msg);}
function audioRequest(msg){var a=_am(msg);var body={text:a.text,speed:parseFloat(a.speed)||1,count:Number(a.count)||2};var ready=Promise.resolve("");if(a.voiceId){body.voice_id=a.voiceId;body.ref_source=a.refSource||audioRefSrcValue();}else if(a.refUrl){body.voice_name=a.refName||a.voiceName||"";ready=fetch(a.refUrl,{cache:"no-store"}).then(function(r){if(!r.ok)throw new Error("参考音频读取失败（HTTP "+r.status+"）");return r.blob();}).then(function(blob){return new Promise(function(res,rej){var fr=new FileReader();fr.onload=function(){res(fr.result);};fr.onerror=function(){rej(new Error("读取参考音频失败"));};fr.readAsDataURL(blob);});});}
return ready.then(function(dataUrl){if(dataUrl)body.reference_audio=dataUrl;return fetch(API+"/api/tts/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});}).then(function(r){return r.json().catch(function(){return{error:"返回解析失败（HTTP "+r.status+"）"};});}).then(function(d){if(!d||d.error){audioSetFailed(msg,(d&&d.error)||"生成失败");return;}
var job=d.job||{};a.jobId=job.id||"";a.status=job.status||"processing";var srvName=d.voice_name||"";if(srvName&&!(srvName==="参考音色"&&a.voiceName&&a.voiceName!=="参考音色")){a.voiceName=srvName;}
if(d.ref_url)a.refUrl=d.ref_url;if(d.ref_source)a.refSource=d.ref_source;msg.status="processing";var el=AS.elByMsg.get(msg);if(el){var chips=el.querySelector(".audio-user-chips");if(chips)chips.innerHTML=_chipsHtml(a);}
_save(false);if(a.jobId)audioPollJob(msg);}).catch(function(e){audioSetFailed(msg,e.message||String(e));});}
function audioPollJob(msg){var a=_am(msg);if(!a.jobId||AS.polls[a.jobId])return;var tick=function(){fetch(API+"/api/tts/job/"+encodeURIComponent(a.jobId),{cache:"no-store"}).then(function(r){return r.json().catch(function(){return{};});}).then(function(d){var job=(d&&d.job)||null;if(!job){audioSetFailed(msg,(d&&d.error)||"任务不存在或已被清理。");return;}
a.candidates=job.candidates||[];a.errors=job.errors||[];a.status=job.status||"processing";msg.status=(a.status==="processing")?"processing":(a.status==="failed"?"failed":"completed");audioPaint(AS.elByMsg.get(msg),msg);if(a.status==="processing"){AS.polls[a.jobId]=setTimeout(tick,1200);}else{delete AS.polls[a.jobId];_save(false);}}).catch(function(){AS.polls[a.jobId]=setTimeout(tick,2000);});};tick();}
async function audioDeleteMsg(msg,el){var a=_am(msg);if(a.jobId&&AS.polls[a.jobId]){clearTimeout(AS.polls[a.jobId]);delete AS.polls[a.jobId];}
if(el){el.querySelectorAll(".ac-audio").forEach(function(au){try{au.pause();}catch(e){}});el.remove();}
if(AS.resultAudio)AS.resultAudio=null;try{AS.elByMsg.delete(msg);}catch(e){}
var _media=(typeof _mediaUrlsOf==="function")?_mediaUrlsOf(msg):[];var _jobs=(a&&a.jobId)?[a.jobId]:[];var sess=_sess();if(sess&&Array.isArray(sess.messages)){var i=sess.messages.indexOf(msg);if(i>=0)sess.messages.splice(i,1);if(!Array.isArray(sess.deletedMsgs))sess.deletedMsgs=[];sess.deletedMsgs.push(_fp(msg));}
var _okSave=true;try{if(typeof saveSessions==="function")_okSave=await saveSessions(true);}catch(e){_okSave=false;}
if(_okSave){if(typeof _purgeMedia==="function")_purgeMedia({urls:_media,ttsJobIds:_jobs});else if(typeof _reclaimMedia==="function")_reclaimMedia(_media);}
var stream=$("stream");if(stream&&!stream.querySelectorAll(".msg").length){var w=$("welcome");if(w)w.style.setProperty("display","");}}
function audioRenderBotMsg(msg){var el=audioBuildSession(msg);var a=_am(msg);if(a.status==="processing"&&a.jobId)audioPollJob(msg);return el;}
window.audioRenderBotMsg=audioRenderBotMsg;var AC_COLORS=["#d9d6ff","#c9f0ee","#ffd9e6","#ffe7c2","#d6ecff","#ffd8d8","#d5f2dd","#f0dcff"];var AC_PLAY_SVG='<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M7.5 4.8 L19 12 L7.5 19.2 Z"/></svg>';var AC_PAUSE_SVG='<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="7" y="5" width="3.8" height="14" rx="1.2"/><rect x="13.2" y="5" width="3.8" height="14" rx="1.2"/></svg>';function _acColor(){return AC_COLORS[Math.floor(Math.random()*AC_COLORS.length)];}
function audioPlaceholderHtml(i){return'<div class="audio-card is-loading" data-idx="'+i+'">'+'<div class="ac-hd"><span class="ac-idx">AI配音 '+(i+1)+'</span><span class="ac-dur">…</span></div>'+'<div class="ac-wave"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div>'+'<div class="ac-skel"></div></div>';}
function audioCardHtml(c,i){var dur=(c.duration!=null)?(Number(c.duration).toFixed(1)+" 秒"):"—";var meta="音色由AI生成"+((c.speed!=null)?(" · 语速 "+fmtSpeed(Number(c.speed))):"");return'<div class="audio-card" data-idx="'+i+'">'+'<button type="button" class="ac-play" title="播放" style="background:'+_esc(c.color||_acColor())+'">'+AC_PLAY_SVG+'</button>'+'<div class="ac-body">'+'<div class="ac-hd"><span class="ac-idx">AI配音 '+(i+1)+'</span><span class="ac-dur">'+_esc(dur)+'</span></div>'+'<div class="ac-prog" title="点击跳转"><span class="ac-prog-fill"></span></div>'+'<div class="ac-foot">'+'<span class="ac-meta">'+_esc(meta)+'</span>'+'<button type="button" class="ac-dl" data-url="'+_esc(c.url)+'" data-name="ai_voice_'+(i+1)+'.mp3">下载</button>'+'</div>'+'</div>'+'<audio class="ac-audio" preload="metadata" src="'+_esc(c.url)+'"></audio>'+'</div>';}
function audioErrorCardHtml(i,msg){return'<div class="audio-card is-error" data-idx="'+i+'">'+'<div class="ac-hd"><span class="ac-idx">AI配音 '+(i+1)+'</span><span class="ac-dur">失败</span></div>'+'<div class="ac-err">'+_esc(msg)+'</div></div>';}
function _pauseCard(card){if(!card)return;var au=card.querySelector(".ac-audio");if(au){try{au.pause();}catch(e){}}
card.classList.remove("playing");var b=card.querySelector(".ac-play");if(b)b.innerHTML=AC_PLAY_SVG;if(AS.resultAudio&&(!au||AS.resultAudio===au))AS.resultAudio=null;}
function audioWireCards(out){out.querySelectorAll(".ac-dl").forEach(function(b){b.addEventListener("click",function(){var a=document.createElement("a");a.href=b.dataset.url;a.download=b.dataset.name||"ai_voice.mp3";document.body.appendChild(a);a.click();a.remove();});});out.querySelectorAll(".ac-play").forEach(function(btn){btn.addEventListener("click",function(){var card=btn.closest(".audio-card");if(!card)return;var au=card.querySelector(".ac-audio");if(!au)return;if(AS.resultAudio&&AS.resultAudio!==au)_pauseCard(AS.resultAudio.closest(".audio-card"));if(AS.resultAudio===au&&!au.paused){_pauseCard(card);return;}
_pauseRefAudio();au.play().catch(function(){});AS.resultAudio=au;card.classList.add("playing");btn.innerHTML=AC_PAUSE_SVG;});});out.querySelectorAll(".ac-prog").forEach(function(bar){bar.addEventListener("click",function(ev){var card=bar.closest(".audio-card");var au=card&&card.querySelector(".ac-audio");if(!au||!au.duration)return;var r=bar.getBoundingClientRect();var pct=Math.max(0,Math.min(1,(ev.clientX-r.left)/r.width));try{au.currentTime=pct*au.duration;}catch(e){}});});out.querySelectorAll(".ac-audio").forEach(function(au){au.addEventListener("timeupdate",function(){var card=au.closest(".audio-card");var fill=card&&card.querySelector(".ac-prog-fill");if(fill){var d=au.duration||0;fill.style.width=d?((au.currentTime/d)*100)+"%":"0%";}});au.addEventListener("ended",function(){_pauseCard(au.closest(".audio-card"));});});}
function audioReturnEdit(meta){try{var st=_state();if(st&&st.media!=="audio"){st.media="audio";var ms=$("media");if(ms)ms.value="audio";}
var pEl=$("prompt");if(pEl){pEl.innerHTML="";pEl.appendChild(document.createTextNode(meta.text||""));}
var sp=$("audioSpeed");if(sp&&meta.speed!=null)sp.value=String(meta.speed);if(typeof refreshSeg==="function")refreshSeg("audioSpeedSel");if(meta&&meta.refUrl&&st){st.assets=(st.assets||[]).filter(function(a){return a.kind!=="audio";});st.assets.push({num:st.assets.length+1,url:meta.refUrl,kind:"audio",name:meta.refName||"参考音色",uploading:false});if(typeof renumberAssets==="function")renumberAssets();if(typeof renderUstrip==="function")renderUstrip();}
if(typeof applyMedia==="function")applyMedia();_resyncPlaceholder();if(pEl)pEl.focus();_toast("已回填到输入框，可修改后重新生成");}catch(e){_toast("回填失败："+e.message);}}
function audioSend(){var text=(typeof getPromptText==="function")?getPromptText():(($("prompt")&&$("prompt").innerText)||"").trim();text=(text||"").trim();if(!text){if($("prompt"))$("prompt").focus();alert("请输入要合成的文字。");return;}
var st=_state();var sess=_sess();if(!sess){_toast("会话尚未就绪，请稍后重试");return;}
var speed=audioSpeedValue();var asset=st&&(st.assets||[]).filter(function(a){return a.kind==="audio"&&a.url&&!a.uploading;})[0];var msg={type:"bot",media:"audio",status:"processing",time:Date.now()/1000,audio:{text:text,speed:parseFloat(speed)||1,count:2,voiceName:asset?(asset.name||"参考音色"):"默认音色",voiceId:asset?(asset.voiceId||""):"",hasRef:!!asset,refUrl:asset?(asset.url||""):"",refName:asset?(asset.name||""):"",refSource:(asset&&asset.voiceId)?audioRefSrcValue():"",status:"processing",jobId:"",candidates:[],errors:[],},};sess.messages.push(msg);try{if(typeof clearPrompt==="function")clearPrompt();}catch(e){}
if(st&&asset){st.assets=(st.assets||[]).filter(function(a){return a.kind!=="audio";});if(typeof renumberAssets==="function")renumberAssets();if(typeof renderUstrip==="function")renderUstrip();_resyncPlaceholder();}
audioBuildSession(msg);_save(false);audioRequest(msg);}
window.audioSend=audioSend;async function ttsProvLoad(){try{var r=await fetch(API+"/api/tts/provider");if(!r.ok)throw new Error("HTTP "+r.status);var d=await r.json();if($("ttsBase"))$("ttsBase").value=d.base_url||"";if($("ttsModel"))$("ttsModel").value=d.model||"";if($("ttsKey")){$("ttsKey").value="";$("ttsKey").placeholder=d.hasKey?(d.api_key_masked||"已配置"):"未配置";}
var src=d.source||{};var txt={ui:"界面配置",env:".env",default:"官方默认"};if($("ttsKeyHint")){$("ttsKeyHint").textContent=d.hasKey?("当前密钥："+(d.api_key_masked||"****")+"（来源："+(txt[src.api_key]||"界面配置")+"）· 留空保存 = 保留原密钥，填新值 = 覆盖 · 仅存本机，不随项目分享"):"尚未配置。密钥仅存本机数据库，不上传、不随项目分享。";}}catch(e){console.error("读取音频配置失败："+e.message);}}
async function ttsProvTest(){var out=$("ttsTestOut"),btn=$("ttsTest");if(btn)btn.disabled=true;if(out){out.className="prov-test-out";out.textContent="测试中…（会真实合成一小段音频）";}
try{var r=await fetch(API+"/api/tts/provider/test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({base_url:($("ttsBase")||{}).value||"",api_key:($("ttsKey")||{}).value||"",model:($("ttsModel")||{}).value||""}),});var d=await r.json();var ms=d.latency_ms?(" · "+Math.round(d.latency_ms)+"ms"):"";if(out){if(d.verdict==="connected"){out.className="prov-test-out ok";out.textContent="连接成功 · 密钥有效"+ms;}
else if(d.verdict==="no_key"){out.className="prov-test-out warn";out.textContent="地址可达 · 尚未配置密钥"+ms;}
else{out.className="prov-test-out bad";out.textContent=(d.detail||"无法连接")+ms;}}}catch(e){if(out){out.className="prov-test-out bad";out.textContent="测试请求失败："+e.message;}}
finally{if(btn)btn.disabled=false;}}
async function ttsProvSave(){var body={base_url:($("ttsBase")||{}).value||"",model:($("ttsModel")||{}).value||""};var kv=($("ttsKey")||{}).value||"";if(kv.trim())body.api_key=kv.trim();var r=await fetch(API+"/api/tts/provider",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});var d=await r.json().catch(function(){return{};});if(!r.ok||d.error)throw new Error(d.error||("HTTP "+r.status));await ttsProvLoad();}
window.ttsProvSave=ttsProvSave;async function provSwitchTab(tab){var key=(tab==="audio")?"audio":((tab==="ark")?"ark":((tab==="ms")?"ms":((tab==="custom")?"custom":"media")));var changed=(window.provActiveTab!==key);if(changed&&window.provDirty&&typeof window.provAskLeave==="function"){var c=await window.provAskLeave("切换后将离开当前页签。","切换");if(c==="cancel")return;if(c==="save"&&typeof provDoSaveSafe==="function"){var ok=await provDoSaveSafe();if(!ok)return;}}
window.provActiveTab=key;if($("provTabMedia"))$("provTabMedia").classList.toggle("on",key==="media");if($("provTabAudio"))$("provTabAudio").classList.toggle("on",key==="audio");if($("provTabArk"))$("provTabArk").classList.toggle("on",key==="ark");if($("provTabMs"))$("provTabMs").classList.toggle("on",key==="ms");if($("provTabCustom"))$("provTabCustom").classList.toggle("on",key==="custom");if($("provPaneMedia"))$("provPaneMedia").style.display=(key==="media")?"":"none";if($("provPaneAudio"))$("provPaneAudio").style.display=(key==="audio")?"":"none";if($("provPaneArk"))$("provPaneArk").style.display=(key==="ark")?"":"none";if($("provPaneMs"))$("provPaneMs").style.display=(key==="ms")?"":"none";if($("provPaneCustom"))$("provPaneCustom").style.display=(key==="custom")?"":"none";if($("provFt"))$("provFt").style.display="";if($("provReset"))$("provReset").style.display="";if(changed){if(key==="audio")ttsProvLoad();else if(key==="ark"){if(typeof window.arkProvLoad==="function")window.arkProvLoad();}
else if(key==="ms"){if(typeof window.msProvLoad==="function")window.msProvLoad();}
else if(key==="custom"){if(typeof window.customProvLoad==="function")window.customProvLoad();}
else if(typeof provLoad==="function")provLoad();window.provDirty=false;}}
window.ttsProvSwitchTab=provSwitchTab;function wireOnce(){if(AS.inited)return;AS.inited=true;audioInitSpeedSeg();audioInitRefSrcSeg();audioWireLibSeg();var _ustrip=$("ustrip");if(_ustrip&&typeof MutationObserver==="function"){new MutationObserver(audioSyncRefSrcVisibility).observe(_ustrip,{childList:true,subtree:true});}
if($("ttsTest"))$("ttsTest").addEventListener("click",ttsProvTest);if($("provTabMedia"))$("provTabMedia").addEventListener("click",function(){provSwitchTab("media");});if($("provTabAudio"))$("provTabAudio").addEventListener("click",function(){provSwitchTab("audio");});if($("provTabArk"))$("provTabArk").addEventListener("click",function(){provSwitchTab("ark");});if($("provTabMs"))$("provTabMs").addEventListener("click",function(){provSwitchTab("ms");});if($("provTabCustom"))$("provTabCustom").addEventListener("click",function(){provSwitchTab("custom");});if($("provBtn"))$("provBtn").addEventListener("click",function(){provSwitchTab("media");});document.addEventListener("mousedown",function(e){if(!AS.itemMenu||!AS.itemMenu.classList.contains("open"))return;if(e.target.closest(".alib-menu")||e.target.closest('[data-act="edit"]'))return;closeItemMenu();});window.addEventListener("resize",closeItemMenu);window.addEventListener("scroll",closeItemMenu,true);audioLoadVoices();try{var st=_state();if(st&&st.media==="audio"&&typeof applyMedia==="function")applyMedia();}catch(e){}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",wireOnce);else wireOnce();try{if(typeof window.audioRenderBotMsg==="function"&&typeof reloadStream==="function"){reloadStream();}}catch(e){}})();