(function(){"use strict";var API=location.origin;var WAV={};function fetchWave(url,buckets){if(!url)return Promise.reject(new Error("waveform: no url"));if(WAV[url])return Promise.resolve(WAV[url]);return fetch(API+"/api/media/waveform",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:url,buckets:buckets||600})}).then(function(r){return r.json();}).then(function(j){if(j&&j.error)throw new Error(j.error);WAV[url]=j;return j;});}
function drawWaveform(cv,peaks,opts){opts=opts||{};var w=cv.clientWidth||cv.width||120;var h=cv.clientHeight||cv.height||46;cv.width=Math.max(2,Math.round(w));cv.height=Math.max(2,Math.round(h));var ctx=cv.getContext("2d");ctx.clearRect(0,0,cv.width,cv.height);if(!peaks||!peaks.length){ctx.strokeStyle=opts.unplayedColor||"#c4b5fd";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,h/2);ctx.lineTo(cv.width,h/2);ctx.stroke();return;}
var cols=Math.max(1,Math.round(cv.width));var n=peaks.length;var vals=new Array(cols);for(var c=0;c<cols;c++){var a0=Math.floor(c*n/cols),a1=Math.max(a0+1,Math.floor((c+1)*n/cols));var m=0;for(var q=a0;q<a1&&q<n;q++)if(peaks[q]>m)m=peaks[q];vals[c]=m;}
var peak=0;for(var k=0;k<cols;k++)if(vals[k]>peak)peak=vals[k];var gain=Math.max(opts.gainMin||0.25,peak||1);var bw=cv.width/cols;var played=(typeof opts.progress==="number")?opts.progress:-1;var pc=opts.playedColor||(opts.big?"#a78bfa":"#5b21b6");var uc=opts.unplayedColor||(opts.big?"rgba(255,255,255,0.30)":"#8b5cf6");var gap=(opts.barGap!=null)?opts.barGap:0.25;for(var i=0;i<cols;i++){var bh=Math.max(1,Math.min(1,vals[i]/gain)*(h-4));ctx.fillStyle=(played>=0&&(i/cols)<=played)?pc:uc;ctx.fillRect(i*bw,(h-bh)/2,Math.max(1,bw-gap),bh);}}
function mountPlayer(cv,audio,opts){opts=opts||{};var url=opts.url||audio.getAttribute("data-wave-url")||audio.src||"";var raf=0;function cur(){return audio.duration?(audio.currentTime/audio.duration):0;}
function paint(){drawWaveform(cv,cv._peaks||[],Object.assign({},opts,{progress:cur()}));}
function loop(){paint();if(!audio.paused)raf=requestAnimationFrame(loop);}
fetchWave(url).then(function(j){cv._peaks=(j&&j.peaks)||[];paint();}).catch(function(){});audio.addEventListener("play",function(){cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);});audio.addEventListener("pause",function(){cancelAnimationFrame(raf);paint();});audio.addEventListener("seeked",paint);audio.addEventListener("ended",function(){cancelAnimationFrame(raf);drawWaveform(cv,cv._peaks||[],Object.assign({},opts,{progress:0}));});cv.addEventListener("click",function(ev){if(!audio.duration)return;var r=cv.getBoundingClientRect();var pct=Math.max(0,Math.min(1,(ev.clientX-r.left)/r.width));try{audio.currentTime=pct*audio.duration;}catch(e){}});return{redraw:paint};}
function mountStatic(cv,url,opts){opts=opts||{};return fetchWave(url).then(function(j){drawWaveform(cv,(j&&j.peaks)||[],opts);return j;}).catch(function(){drawWaveform(cv,[],opts);});}
window.Wave={fetchWave:fetchWave,drawWaveform:drawWaveform,mountPlayer:mountPlayer,mountStatic:mountStatic};})();