(function(){"use strict";var API=location.origin;function esc(s){return String(s==null?"":s).replace(/[&<>"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c];});}
function fmtTime(t){if(!t)return"—";var d=new Date(t*1000);function p(n){return(n<10?"0":"")+n;}
return d.getFullYear()+"-"+p(d.getMonth()+1)+"-"+p(d.getDate())+" "+p(d.getHours())+":"+p(d.getMinutes());}
var S={projects:[],batching:false,picked:{}};function miniThumb(p){var ns=p.mini_nodes||[],es=p.mini_edges||[];if(!ns.length)return'<div style="height:100%;display:flex;align-items:center;justify-content:center;color:#c4b5fd;font-size:12px">空项目 · 双击画布开始</div>';var minX=1e9,minY=1e9,maxX=-1e9,maxY=-1e9;ns.forEach(function(n){minX=Math.min(minX,n.x);minY=Math.min(minY,n.y);maxX=Math.max(maxX,n.x+(n.w||140));maxY=Math.max(maxY,n.y+(n.h||60));});var pad=30,w=Math.max(1,maxX-minX+pad*2),h=Math.max(1,maxY-minY+pad*2);var idx={};ns.forEach(function(n,i){idx[n.id]=i;});var lines=es.map(function(e){var a=ns[idx[e.a]],b=ns[idx[e.b]];if(!a||!b)return"";var x1=a.x-minX+pad+(a.w||140),y1=a.y-minY+pad+(a.h||60)/2;var x2=b.x-minX+pad,y2=b.y-minY+pad+(b.h||60)/2;return'<path d="M'+x1+' '+y1+' C '+(x1+26)+' '+y1+', '+(x2-26)+' '+y2+', '+x2+' '+y2+'" stroke="#b9a5ec" stroke-width="2.5" fill="none"/>';}).join("");var boxes=ns.map(function(n){var x=n.x-minX+pad,y=n.y-minY+pad,w=n.w||140,hh=n.h||60;var fill=n.t==="txt"?"#fff7df":(n.t==="asset"?"#e4dcfa":"#ede9fe");var head=n.t==="txt"?"#f0dfae":"#7c3aed";return'<g><rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+hh+'" rx="6" fill="'+fill+'" stroke="#c9b8f5"/>'+'<rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+Math.min(12,hh/4)+'" rx="6" fill="'+head+'" opacity="0.85"/></g>';}).join("");return'<svg viewBox="0 0 '+w+' '+h+'" preserveAspectRatio="xMidYMid meet">'+lines+boxes+'</svg>';}
function render(){var root=document.getElementById("canvasPanelView");if(!root)return;var h='<div class="cv-head"><h2>画布</h2><div class="sp"></div>'+'<button class="cv-batch'+(S.batching?" on":"")+'" id="cvBatchBtn">'+(S.batching?"退出批量":"☑ 批量管理")+'</button></div>'+'<div class="cv-grid'+(S.batching?" batching":"")+'" id="cvGrid">'+'<div class="cv-add" id="cvAdd"><div class="plus">＋</div><span>新建画布项目</span></div>';if(!S.projects.length)h+='<div class="cv-empty">还没有画布项目——点上方「新建画布项目」开始</div>';S.projects.forEach(function(p){var on=!!S.picked[p.id];h+='<div class="cv-card'+(on?" picked":"")+'" data-id="'+p.id+'">'+'<div class="cv-shot">'+miniThumb(p)+'<div class="cv-name-bar">'+'<b class="cv-title" title="'+esc(p.name)+'">'+esc(p.name)+'</b>'+'<button class="cv-rn" data-rn="'+p.id+'" aria-label="重命名" title="重命名">✎</button>'+'</div>'+'<div class="cv-meta-bar">'+'<span>'+fmtTime(p.created_at)+'</span>'+'<span>'+(p.node_count||0)+' 节点</span>'+'</div>'+
(S.batching?'<input type="checkbox" class="cv-chk" data-chk="'+p.id+'"'+(on?" checked":"")+'>':"")+'</div>'+'</div>';});h+='</div>';if(S.batching){var n=Object.keys(S.picked).length;h+='<div class="cv-bar"><button id="cvAll">全选</button><button id="cvNone">取消全选</button>'+'<button class="danger" id="cvDel">删除选中（'+n+'）</button><button id="cvExitBatch">退出批量</button></div>';}
root.innerHTML=h;wire();}
function load(){return fetch(API+"/api/canvas/projects").then(function(r){return r.json();}).then(function(j){S.projects=(j&&j.projects)||[];render();}).catch(function(e){console.warn("[canvas] 列表加载失败",e);});}
function createProject(){fetch(API+"/api/canvas/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}).then(function(r){return r.json();}).then(function(doc){if(doc&&doc.id&&window.CANVAS_STAGE){window.CANVAS_STAGE.openProject(doc.id,doc);}else{load();}}).catch(function(e){alert("新建画布项目失败："+e.message);});}
function rename(id,cur){var name=prompt("项目名称：",cur||"");if(name===null)return;name=name.trim()||"未命名";fetch(API+"/api/canvas/projects/"+id).then(function(r){return r.json();}).then(function(doc){doc.name=name;return fetch(API+"/api/canvas/projects/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(doc)});}).then(load).catch(function(e){alert("重命名失败："+e.message);});}
function batchDelete(){var ids=Object.keys(S.picked);if(!ids.length)return;if(!confirm("删除选中的 "+ids.length+" 个画布项目？\n项目内的任务记录将一并删除（不可恢复）；已生成的结果仍保留在资产库。"))return;fetch(API+"/api/canvas/projects",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids:ids})}).then(function(){S.picked={};load();}).catch(function(e){alert("删除失败："+e.message);});}
function wire(){var root=document.getElementById("canvasPanelView");if(!root||root.dataset.cvWired==="1"){bindDynamic();return;}
root.dataset.cvWired="1";root.addEventListener("click",function(e){var add=e.target.closest("#cvAdd");if(add){createProject();return;}
var bb=e.target.closest("#cvBatchBtn");if(bb){S.batching=!S.batching;S.picked={};render();return;}
if(S.batching){var card=e.target.closest(".cv-card");if(card){var cid=card.getAttribute("data-id");if(S.picked[cid])delete S.picked[cid];else S.picked[cid]=true;var on=!!S.picked[cid];card.classList.toggle("picked",on);var cb=card.querySelector(".cv-chk");if(cb)cb.checked=on;var del=document.getElementById("cvDel");if(del)del.textContent="删除选中（"+Object.keys(S.picked).length+"）";return;}
if(e.target.closest("#cvAll")){S.projects.forEach(function(p){S.picked[p.id]=true;});render();return;}
if(e.target.closest("#cvNone")){S.picked={};render();return;}
if(e.target.closest("#cvDel")){batchDelete();return;}
if(e.target.closest("#cvExitBatch")){S.batching=false;S.picked={};render();return;}
return;}
var rn=e.target.closest("[data-rn]");if(rn){e.stopPropagation();var p=S.projects.find(function(x){return x.id===rn.getAttribute("data-rn");});rename(rn.getAttribute("data-rn"),p&&p.name);return;}
var card2=e.target.closest(".cv-card");if(card2){var pid=card2.getAttribute("data-id");if(window.CANVAS_STAGE)window.CANVAS_STAGE.openProject(pid);return;}});bindDynamic();}
function bindDynamic(){}
function open(){Views.show("canvas");load();}
function close(){Views.show("session");}
window.CANVAS={open:open,close:close,refresh:load};function wireEntry(){var b=document.getElementById("canvasBtn");if(b&&!b.dataset.cvWired){b.dataset.cvWired="1";b.addEventListener("click",function(){if(Views.cur==="canvas")close();else open();});}}
var CV_LAST_KEY="cv_last_project";function cvForgetLast(){try{localStorage.removeItem(CV_LAST_KEY);}catch(e){}}
if(window.Views){Views.registerOpener("canvas",function(){if(window.CANVAS)window.CANVAS.open();});Views.registerOpener("editor",function(){var last=null;try{last=localStorage.getItem(CV_LAST_KEY);}catch(e){}
if(!window.CANVAS)return;if(!last||!window.CANVAS_STAGE){window.CANVAS.open();return;}
fetch(API+"/api/canvas/projects").then(function(r){return r.json();}).then(function(j){var list=(j&&(j.projects||j.items))||[];if(!list.some(function(x){return x.id===last;})){cvForgetLast();window.CANVAS.open();return;}
window.CANVAS.open();window.CANVAS_STAGE.openProject(last);}).catch(function(){window.CANVAS.open();});});}
wireEntry();if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",wireEntry);})();