(function(){"use strict";var API=location.origin;function esc(s){return String(s==null?"":s).replace(/[&<>"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c];});}
var _thumb=(u,w)=>(typeof thumbUrl==="function"?thumbUrl(u,w):u);var S={doc:null,sel:null,linking:null,dirty:false,saveTimer:null,vp:{x:0,y:0,zoom:1},cfg:null,polls:{},edgeSel:null,selSet:[],marquee:null,undoStack:[],redoStack:[],clipboard:null,_dragSnap:null,_txtSnap:null,_txtNode:null,_txtVal:null};var NODE_DEFS={asset:{label:"素材",icon:"ic-image",w:150,h:96,head:"素材",ports:{out:true}},txt:{label:"文本",icon:"ic-pencil",w:180,h:110,head:"文本",ports:{out:true}},image_gen:{label:"图片生成",icon:"ic-image",w:190,h:96,head:"图片生成",ports:{in:true,out:true}},video_gen:{label:"视频生成",icon:"ic-vgen",w:190,h:96,head:"视频生成",ports:{in:true}},audio_gen:{label:"音频生成",icon:"ic-audio",w:190,h:80,head:"音频生成",ports:{in:true}},timeline:{label:"视频合成",icon:"ic-vcompose",w:520,h:240,head:"视频合成",ports:{in:true}}};function headTitle(n){var def=NODE_DEFS[n.type];if(n.type==="timeline"){var nm=(window.Timeline&&window.Timeline.selName)?window.Timeline.selName(n):"";return nm||("视频合成 "+(window.Timeline?window.Timeline.seqOf(S.doc.nodes,n.id):1));}
if(n.type==="asset")return n.data.name||def.head;if(n.data.result&&n.data.result.length){var name=String(n.data.result[0]).split("?")[0].split("/").pop();try{name=decodeURIComponent(name);}catch(e){}
if(name)return name;}
return def.head;}
function cvFirstVideoModel(){var list=(typeof MEDIA_MODES!=="undefined"&&MEDIA_MODES.video&&MEDIA_MODES.video.models)||[];return list.length?(list[0].value||list[0]):"";}
function modelVideoCaps(model){var lim=(typeof MODEL_LIMITS!=="undefined"&&MODEL_LIMITS[model])||null;if(!lim)lim=(typeof MODEL_LIMITS!=="undefined"&&MODEL_LIMITS[cvFirstVideoModel()])||null;if(lim){return{image:(lim.max_images!=null)?lim.max_images:0,audio:(lim.max_audios!=null)?lim.max_audios:0,video:lim.allow_video?1:0};}
return{image:0,audio:0,video:0};}
function nodeCaps(n){if(n.type==="image_gen"){var m=n.data.model||"";var ark=(typeof ARK_IMAGE_TIERS!=="undefined"&&ARK_IMAGE_TIERS&&ARK_IMAGE_TIERS[m])||null;var im=(typeof IMAGE_MODEL_LIMITS!=="undefined"&&IMAGE_MODEL_LIMITS[m])||{};return{image:(ark&&ark.max_ref_images)||im.max_images||99,audio:0,video:0};}
if(n.type==="video_gen"){return modelVideoCaps(n.data.model);}
if(n.type==="audio_gen"){return{image:0,audio:1,video:0};}
return{image:0,audio:0,video:0};}
function cvImgRatios(model){try{if(typeof imageRatiosForImageModel==="function"){var r=imageRatiosForImageModel(model);if(r&&r.length)return r;}}catch(e){}
return(MEDIA_MODES.image&&MEDIA_MODES.image.aspects)||[];}
function cvImgSizes(model,ratio){try{if(typeof imageSizesForImageModel==="function"){var s=imageSizesForImageModel(model,ratio);if(s&&s.length)return s;}}catch(e){}
return(MEDIA_MODES.image&&MEDIA_MODES.image.sizes)||["1K","2K","3K","4K"];}
function cvClampGear(n){try{if(n.type==="image_gen"){var ir=cvImgRatios(n.data.model);if(ir.length&&ir.indexOf(n.data.ratio)<0)n.data.ratio=ir[0];var isz=cvImgSizes(n.data.model,n.data.ratio);if(isz.length&&isz.indexOf(n.data.size)<0)n.data.size=isz[0];}else if(n.type==="video_gen"){var vasps=(MEDIA_MODES.video&&MEDIA_MODES.video.aspects)||[];if(vasps.length&&vasps.indexOf(n.data.ratio)<0)n.data.ratio=vasps[0];var vlim=(typeof MODEL_LIMITS!=="undefined"&&MODEL_LIMITS[n.data.model])||{};var vsz=((typeof MODEL_SIZES!=="undefined"&&MODEL_SIZES[n.data.model])||vlim.sizes||["720P"]);var vcur=String(n.data.size||"720P").toUpperCase();if(vsz.map(function(x){return String(x).toUpperCase();}).indexOf(vcur)<0)n.data.size=vsz[0];var vlo=vlim.min_seconds||4,vhi=vlim.max_seconds||12;if(typeof n.data.seconds==="number")n.data.seconds=Math.max(vlo,Math.min(vhi,n.data.seconds));}}catch(e){}}
function inboundKindCount(nid,kind){return S.doc.edges.filter(function(e){if(e.to!==nid)return false;var a=nodeById(e.from);return!!(a&&a.type==="asset"&&a.data.kind===kind&&a.data.url);}).length;}
var LOCKED_REF_MSG="当前状态不可接入新素材";function refLocked(n){return!!(n&&(n.type==="image_gen"||n.type==="video_gen"||n.type==="audio_gen")&&n.data&&n.data.status==="done");}
function edgeReject(from,to){var f=from.type,t=to.type;if(refLocked(to))return LOCKED_REF_MSG;if(t==="timeline"&&(f==="asset"||f==="image_gen"||f==="video_gen"||f==="audio_gen"))return null;if(f==="txt"&&(t==="image_gen"||t==="video_gen"||t==="audio_gen"))return null;if(f==="image_gen"&&t==="video_gen")return(from.data.result&&from.data.result.length)?null:"该图片节点还没有生成结果";if(f==="asset"&&(t==="image_gen"||t==="video_gen"||t==="audio_gen")){var k=from.data.kind||"image",caps=nodeCaps(to);var cap=(k==="audio")?caps.audio:(k==="video")?caps.video:caps.image;if(!cap){var what=k==="audio"?"参考音频":(k==="video"?"参考视频":"参考图");var why=(t==="audio_gen")?"音频生成只接受音频素材（音色克隆需要一段参考音频）":(t==="image_gen")?"生图只接受图片素材":(k==="video")?"当前模型不支持参考视频（仅 Agnes 2.5 Video 支持）":"当前模型不接受该素材";return what+"不支持："+why;}
var used=inboundKindCount(to.id,k);if(used>=cap){return"已达当前模型上限——"+(k==="audio"?"参考音频":(k==="video"?"参考视频":"参考图"))+"最多 "+cap+" 个（已接入 "+used+" 个）";}
return null;}
return"这种连线不符合画布规则（素材/文本 → 生成节点；图片生成结果 → 视频生成）";}
function edgeAllowed(fromNode,toNode){return!edgeReject(fromNode,toNode);}
function edgeKind(fromNode,toNode){if(fromNode.type==="txt")return"txt_merge";if(fromNode.type==="asset"&&fromNode.data.kind==="audio"&&toNode.type==="audio_gen")return"voice_ref";return"asset_ref";}
function openProject(pid,presetDoc){var stage=document.getElementById("canvasStage");if(!stage)return;Views.show("editor");var load=presetDoc?Promise.resolve(presetDoc):fetch(API+"/api/canvas/projects/"+pid).then(function(r){return r.json();});load.then(function(doc){if(!doc||!doc.id)throw new Error("项目不存在");console.log("[canvas-stage] openProject 渲染开始",doc.id);S.doc=doc;var wFixed=false;(S.doc.nodes||[]).forEach(function(nd){if(nd.type==="asset"&&nd.data&&nd.data.kind==="audio"&&(!nd.w||nd.w<250)){nd.w=250;wFixed=true;}});if(wFixed)scheduleSave();S.vp=doc.viewport||{x:0,y:0,zoom:1};cvRemember(doc.id);initTimelineBridge();renderStage();(S.doc.nodes||[]).forEach(function(nd){if(nd.data&&nd.data.status==="processing"&&nd.data.task_ref){if(nd.type==="audio_gen")startTtsPoll(nd.id,nd.data.task_ref);else if(nd.type==="image_gen"||nd.type==="video_gen")
startPoll(nd.id,nd.data.task_ref,nd.data.model);}});loadConfig();}).catch(function(e){console.error("[canvas-stage] openProject 失败:",e&&e.message);cvForget();closeStage();alert("打开画布失败："+e.message);});}
function initTimelineBridge(){if(!window.Timeline||window.Timeline.__wired)return;window.Timeline.__wired=true;window.Timeline.init({save:function(){scheduleSave();},render:function(){renderNodes();renderEdges();},renderPanels:function(){renderNodes();renderEdges();},snapshot:function(){return snapshotDoc();},push:function(st){pushHistory(st);},undo:function(){undo();},redo:function(){redo();},canUndo:function(){return S.undoStack.length>0;},canRedo:function(){return S.redoStack.length>0;},nodeById:function(id){return nodeById(id);},selected:function(){return nodeById(S.sel);},zoom:function(){return(S.vp&&S.vp.zoom)||1;},canvasAssets:cvCanvasAssets,linkEdge:function(fromId,toId){return cvLinkEdge(fromId,toId);},addAssetNode:function(tlId,item,redraw){return cvAddAssetNode(tlId,item,redraw);},incomingEdges:function(tlId){return(S.doc?S.doc.edges:[]).filter(function(e){return e.to===tlId;}).map(function(e){return{id:e.id,from:e.from,kind:e.kind};});},renderEdges:function(){renderEdges();},removeEdge:function(edgeId){if(!S.doc)return false;var before=S.doc.edges.length;S.doc.edges=S.doc.edges.filter(function(x){return x.id!==edgeId;});if(S.doc.edges.length===before)return false;if(S.edgeSel===edgeId)S.edgeSel=null;return true;},toast:function(msg){cvToast(msg);},syncTitle:function(nodeId){var n=nodeById(nodeId);if(!n)return;var el=document.querySelector('#csNodes .cs-node[data-node="'+nodeId+'"] .nd-title .t-tx');if(!el)return;var want=headTitle(n);if(el.textContent===want)return;el.textContent=want;fitTitles();}});}
function cvCanvasAssets(){var out=[];(S.doc?S.doc.nodes:[]).forEach(function(n){if(!n.data)return;if(n.type==="asset"&&n.data.url){out.push({nodeId:n.id,url:n.data.url,kind:n.data.kind||"image",name:n.data.name||"",gen:false});}else if(n.type==="image_gen"||n.type==="video_gen"||n.type==="audio_gen"){var kind=n.type==="audio_gen"?"audio":(n.type==="video_gen"?"video":"image");(n.data.result||[]).forEach(function(u,i){if(!u)return;var nm=(n.data.name||(kind==="audio"?"音频":(kind==="video"?"视频":"图片")));out.push({nodeId:n.id,url:u,kind:kind,gen:true,name:nm+((n.data.result||[]).length>1?(" "+(i+1)):"")});});}});return out;}
function cvLinkEdge(fromId,toId){if(!S.doc||!fromId||!toId||fromId===toId)return false;var a=nodeById(fromId),b=nodeById(toId);if(!a||!b)return false;if(!edgeAllowed(a,b))return false;var dup=S.doc.edges.some(function(e){return e.from===fromId&&e.to===toId;});if(dup)return false;S.doc.edges.push({id:newId("e"),from:fromId,to:toId,kind:edgeKind(a,b)});return true;}
function cvAddAssetNode(tlId,item,redraw){var tl=nodeById(tlId);if(!S.doc||!tl||!item||!item.url)return"";var kind=item.kind||"image";var h=NODE_DEFS.asset.h;var k=(S.doc.edges||[]).filter(function(e){return e.to===tlId;}).length;var a={id:newId("n"),type:"asset",x:Math.round(tl.x+tl.w+60),y:Math.round(tl.y+k*(h+24)),w:assetNodeWidth(kind),h:h,data:{kind:kind,url:item.url,name:item.name||"素材"}};S.doc.nodes.push(a);if(redraw){renderNodes();renderEdges();}
return a.id;}
function cvToast(msg){var t=document.getElementById("cvToast");if(!t){t=document.createElement("div");t.id="cvToast";document.body.appendChild(t);}
t.textContent=msg||"";t.className="cv-toast show";clearTimeout(cvToast._t);cvToast._t=setTimeout(function(){t.className="cv-toast";},2600);}
function closeStage(){if(window.Timeline)window.Timeline.stopAll();S.doc=null;S.sel=null;S.linking=null;S.edgeSel=null;S.selSet=[];S.marquee=null;Object.keys(S.polls).forEach(stopPoll);if(window.MediaStop)window.MediaStop.stopAll("canvas:closeStage");if(window.UISeg){UISeg.close();UISeg.purge("cvp_");}
cvCloseArsec();cvHideAtPop();if(window.CANVAS&&window.CANVAS.refresh)window.CANVAS.refresh();cvForget();Views.show("canvas");}
var CV_LAST_KEY="cv_last_project";function cvRemember(pid){try{if(pid)localStorage.setItem(CV_LAST_KEY,pid);}catch(e){}}
function cvForget(){try{localStorage.removeItem(CV_LAST_KEY);}catch(e){}}
function loadConfig(){if(S.cfg)return;fetch(API+"/api/config").then(function(r){return r.json();}).then(function(c){S.cfg=c;if(S.doc)renderPanel();}).catch(function(){});}
function imgModels(){return(S.cfg&&(S.cfg.modelLimits?Object.keys(S.cfg.modelLimits):null))||[];}
function renderStage(){var stage=document.getElementById("canvasStage");stage.innerHTML='<div class="cs-top">'+'<button class="back" id="csBack" type="button" title="返回项目管理页"><span class="ic ic-chevron-left" aria-hidden="true"></span><span>返回</span></button>'+'<span class="ttl">'+esc(S.doc.name||"未命名")+'</span><span class="sp"></span>'+'<span class="save" id="csSave">✓ 已保存</span></div>'+'<div class="cs-work" id="csWork"><div class="cs-vp" id="csVp">'+'<svg class="cs-edges" id="csEdges"></svg>'+'<div id="csNodes"></div>'+'<svg id="csGuides"></svg>'+'</div></div>'+'<div class="cs-bottom">'+'<button class="cs-bbtn" id="csAddBtn" title="添加节点"><span class="ic ic-plus"></span><span class="tip">添加节点</span></button>'+'<button class="cs-bbtn off" id="csSnapBtn" title="参考对齐（开关）"><span class="ic ic-snap"></span><span class="tip">参考对齐</span></button>'+'<button class="cs-bbtn" id="csFitBtn" title="适应视图（显示所有节点）"><span class="ic ic-fit"></span><span class="tip">适应视图</span></button>'+'</div>';document.getElementById("csBack").addEventListener("click",closeStage);document.getElementById("csAddBtn").addEventListener("click",function(e){e.stopPropagation();openMenuAtBtn(this);});document.getElementById("csFitBtn").addEventListener("click",function(){fitView();});S.snapEnabled=false;document.getElementById("csSnapBtn").addEventListener("click",function(){S.snapEnabled=!S.snapEnabled;this.classList.toggle("off",!S.snapEnabled);if(!S.snapEnabled)clearGuides();});renderNodes();renderEdges();applyViewport();wireWork();}
function applyViewport(){var vp=document.getElementById("csVp");if(vp)vp.style.transform="translate("+S.vp.x+"px,"+S.vp.y+"px) scale("+S.vp.zoom+")";}
function nodeHtml(n){var def=NODE_DEFS[n.type];var sel=(S.sel===n.id||(S.selSet||[]).indexOf(n.id)>=0)?" sel":"";var body="";if(n.type==="asset"){var isA=n.data.kind==="audio",isV=n.data.kind==="video";body=(isA)?'<div class="nd-audio-item"><canvas class="nd-wave" data-wave-url="'+esc(n.data.url)+'" width="220" height="34"></canvas><audio src="'+esc(n.data.url)+'" controls style="width:100%"></audio></div>':(isV?(n.data.url?'<video class="nd-thumb" src="'+esc(n.data.url)+'" controls preload="metadata"></video>':'<div class="nd-ph"><span class="ph-ic"><span class="ic ic-video"></span></span><span class="ph-tx">视频</span></div>'):(n.data.url?'<img class="nd-thumb" src="'+esc(_thumb(n.data.url,320))+'" alt="">':'<div class="nd-ph"><span class="ph-ic"><span class="ic ic-image"></span></span><span class="ph-tx">图片</span></div>'));}else if(n.type==="txt"){body='<textarea data-txt="'+n.id+'" placeholder="输入文本…可连线并入生成节点提示词">'+esc(n.data.text||"")+'</textarea><div class="rsz" data-rsz="'+n.id+'"></div>';}else if(n.type==="image_gen"||n.type==="video_gen"){var st=n.data.status;var stx=st==="processing"?'<div class="nd-status run"><span class="ic ic-loader"></span> 生成中…</div>':st==="error"?'<div class="nd-status err"><span class="ic ic-fail"></span> '+esc((n.data.error||"失败").slice(0,30))+'</div>':"";var res="";if(n.type==="image_gen"&&n.data.result&&n.data.result.length){res='<img class="nd-thumb" src="'+esc(_thumb(n.data.result[0],640))+'" alt="">';}else if(n.type==="video_gen"&&n.data.result&&n.data.result.length){res='<video class="nd-thumb" src="'+esc(n.data.result[0])+'" controls></video>';}else if(!stx){var isVid=n.type==="video_gen";res='<div class="nd-ph"><span class="ph-ic"><span class="ic '+(isVid?"ic-film":"ic-image")+'"></span></span><span class="ph-tx">'+(isVid?"视频":"图片")+'</span></div>';}
body=res+stx;}else if(n.type==="audio_gen"){var st2=n.data.status;var stx2=st2==="processing"?'<div class="nd-status run"><span class="ic ic-loader"></span> 生成中…</div>':st2==="error"?'<div class="nd-status err"><span class="ic ic-fail"></span> '+esc((n.data.error||"失败").slice(0,30))+'</div>':"";var aInner;if(n.data.result&&n.data.result.length){aInner=n.data.result.map(function(u,i){return'<div class="nd-audio-item">'
+'<div class="nd-audio-cap">候选 '+(i+1)+'</div>'
+'<canvas class="nd-wave" data-wave-url="'+esc(u)+'" width="220" height="30"></canvas>'
+'<audio src="'+esc(u)+'" controls style="width:100%"></audio>'
+'</div>';}).join("");}else{aInner=stx2||'<div class="nd-ph"><span class="ph-ic"><span class="ic '+def.icon+'"></span></span><span class="ph-tx">'+esc(def.label)+'</span></div>';}
body=aInner;}else if(n.type==="timeline"){body=(window.Timeline&&window.Timeline.bodyHtml)?window.Timeline.bodyHtml(n):'<div class="tl-panel" data-tl-node="'+n.id+'"><div class="tl-empty">时间线模块未加载</div></div>';}
var ports="";if(def.ports.in)ports+='<span class="cs-port in" data-pin="'+n.id+'"></span>';if(def.ports.out)ports+='<span class="cs-port out" data-pout="'+n.id+'"></span>';var hStyle=(n.type==="txt"&&n.h)?";height:"+n.h+"px":"";return'<div class="cs-node'+(n.type==="txt"?" txt":(n.type==="asset"?" asset":""))+sel+'" data-node="'+n.id+'" style="left:'+n.x+'px;top:'+n.y+'px;width:'+n.w+'px'+hStyle+'">'+'<div class="nd-head"><span class="ic '+(n.type==="asset"?(n.data.kind==="audio"?"ic-audio":(n.data.kind==="video"?"ic-video":"ic-image")):def.icon)+'"></span><span class="nd-title"><span class="t-tx">'+esc(headTitle(n))+'</span></span></div>'+'<div class="nd-body">'+body+'</div>'+ports+'</div>';}
function renderNodes(){var box=document.getElementById("csNodes");if(!box||!S.doc)return;box.innerHTML=S.doc.nodes.map(nodeHtml).join("");fitTitles();mountTimelines();mountAudioWaves();renderPanel();}
function mountAudioWaves(){if(!window.Wave||!S.doc)return;document.querySelectorAll("#csNodes .nd-audio-item").forEach(function(it){var cv=it.querySelector("canvas.nd-wave");if(!cv)return;var au=it.querySelector("audio");if(au)window.Wave.mountPlayer(cv,au,{url:cv.getAttribute("data-wave-url")});else window.Wave.mountStatic(cv,cv.getAttribute("data-wave-url"));});}
function mountTimelines(){if(!window.Timeline||!S.doc)return;S.doc.nodes.forEach(function(n){if(n.type!=="timeline")return;var el=document.querySelector('.tl-panel[data-tl-node="'+n.id+'"]');if(el)window.Timeline.mount(el);});}
function fitTitles(){document.querySelectorAll("#csNodes .nd-title").forEach(function(t){var over=t.scrollWidth-t.clientWidth;if(over>2){t.classList.add("scr");t.style.setProperty("--scr-x",(over+4)+"px");}else{t.classList.remove("scr");t.style.removeProperty("--scr-x");}});}
function nodeById(id){return S.doc.nodes.find(function(n){return n.id===id;})||null;}
function portPos(n,side){var el=document.querySelector('[data-node="'+n.id+'"]');var vp=document.getElementById("csVp");if(el&&vp&&S.vp.zoom){var r=el.getBoundingClientRect(),vr=vp.getBoundingClientRect();var wx=(r.left-vr.left)/S.vp.zoom,wy=(r.top-vr.top)/S.vp.zoom;var ww=r.width/S.vp.zoom,wh=r.height/S.vp.zoom;return side==="out"?{x:wx+ww,y:wy+wh/2}:{x:wx,y:wy+wh/2};}
return side==="out"?{x:n.x+n.w,y:n.y+n.h/2}:{x:n.x,y:n.y+n.h/2};}
function bezMid(p0,c1,c2,p3){return{x:(p0.x+3*c1.x+3*c2.x+p3.x)/8,y:(p0.y+3*c1.y+3*c2.y+p3.y)/8};}
function renderEdges(){var svg=document.getElementById("csEdges");if(!svg||!S.doc)return;var h="";var selIds=[];if(S.sel)selIds.push(S.sel);(S.selSet||[]).forEach(function(id){if(selIds.indexOf(id)<0)selIds.push(id);});S.doc.edges.forEach(function(e){var a=nodeById(e.from),b=nodeById(e.to);if(!a||!b)return;var p0=portPos(a,"out"),p3=portPos(b,"in");var c1={x:p0.x+40,y:p0.y},c2={x:p3.x-40,y:p3.y};var dash=e.kind==="txt_merge"?' stroke-dasharray="6 4"':(e.kind==="voice_ref"?' stroke-dasharray="2 4"':"");var selCls=S.edgeSel===e.id?" sel":"";var d="M"+p0.x+" "+p0.y+" C "+c1.x+" "+c1.y+", "+c2.x+" "+c2.y+", "+p3.x+" "+p3.y;h+='<path class="cs-edge'+selCls+'" data-edge="'+e.id+'" d="'+d+'" stroke="'+(e.kind==="voice_ref"?"#0d9488":e.kind==="txt_merge"?"#d97706":"#8b5cf6")+'" stroke-width="'+(S.edgeSel===e.id?4:2.5)+'" stroke-linecap="round" fill="none"'+dash+'><title>'+esc(e.kind)+'（单击选中，再点 × 删除）</title></path>';if(selIds.indexOf(e.from)>=0||selIds.indexOf(e.to)>=0){h+='<path class="cs-edge-flow" d="'+d+'" fill="none"/>';}
if(S.edgeSel===e.id){var mid=bezMid(p0,c1,c2,p3);h+='<g class="cs-edge-del" data-edel="'+e.id+'" transform="translate('+Math.round(mid.x)+','+Math.round(mid.y)+')" title="删除这条连线">'+'<circle r="10" fill="#dc2626" stroke="#fff" stroke-width="2"/>'+'<path d="M18 6 6 18" stroke="#fff" stroke-width="2.5" stroke-linecap="round" transform="scale(0.5) translate(-12,-12)"/>'+'<path d="m6 6 12 12" stroke="#fff" stroke-width="2.5" stroke-linecap="round" transform="scale(0.5) translate(-12,-12)"/></g>';}});svg.setAttribute("width",6000);svg.setAttribute("height",4000);svg.innerHTML=h;}
function capOverHint(n){var caps=nodeCaps(n),msgs=[];[["image","参考图",caps.image],["audio","参考音频",caps.audio],["video","参考视频",caps.video]].forEach(function(r){var used=inboundKindCount(n.id,r[0]);if(used>r[2])msgs.push(r[1]+"上限 "+r[2]+" 个，已接入 "+used+" 个");});if(!msgs.length)return null;return"当前模型："+msgs.join("；")+"——发送时按上限取前面几个，多余的请断开连线。";}
function renderPanel(){var old=document.getElementById("csStagePanel");if(old)old.remove();if(window.UISeg){UISeg.close();UISeg.purge("cvp_");}
cvCloseArsec();cvHideAtPop();var n=nodeById(S.sel);if(!n||!S.doc)return;if(n.type==="txt")return;var vp=document.getElementById("csVp");if(!vp)return;var panel=document.createElement("div");panel.className="cs-panel";panel.id="csStagePanel";if(n.type==="asset"){var refs=S.doc.edges.filter(function(e){return e.from===n.id;}).length;var isAudio=n.data.kind==="audio",isVideoAsset=n.data.kind==="video";panel.innerHTML='<div class="ie-row"><button class="ie-btn" id="csPvView">资产库中查看</button>'+
(!isAudio&&!isVideoAsset&&n.data.url?'<button class="ie-btn" id="csPvEdit"><span class="ic ic-pencil"></span> 图片编辑</button>':'')+'</div>'+'<div class="ie-row" style="color:var(--mut,#6b7280);font-size:11px">'+(refs?'连到 '+refs+' 个生成节点':'尚未连接到任何生成节点')+'</div>';var editBtn=panel.querySelector("#csPvEdit");if(editBtn)editBtn.addEventListener("click",function(){openImageEditForNode(n);});}else if(n.type==="image_gen"||n.type==="video_gen"||n.type==="audio_gen"){var base=document.querySelector(".composer .comp-card");if(!base){panel.remove();return;}
var card=base.cloneNode(true);card.querySelectorAll("[data-page-node-id]").forEach(function(x){x.removeAttribute("data-page-node-id");});card.querySelectorAll("[id]").forEach(function(x){x.id="cvp_"+x.id;});card.querySelectorAll("[disabled]").forEach(function(x){x.removeAttribute("disabled");});card.querySelectorAll(".seg, .kf-area, .up-area, .upload-strip, .icon-btn, .bar-sep, .send-row, .editable, #cvp_atChip, #cvp_upIconBtn").forEach(function(x){x.style.display="";});card.querySelectorAll(".seg[data-seg]").forEach(function(sg){var ds=sg.getAttribute("data-seg");sg.setAttribute("data-seg","cvp_"+ds);var pop=sg.querySelector(".seg-pop");if(pop)pop.setAttribute("data-seg","cvp_"+ds);});var isKf=(n.type==="video_gen"&&n.data.mode==="keyframe");var kill=["#cvp_phLayer","#cvp_mediaSel","#cvp_arsec"];if(n.type!=="audio_gen")kill.push("#cvp_audioLibSel","#cvp_audioSpeedSel","#cvp_audioRefSrcSel");if(n.type!=="image_gen")kill.push("#cvp_styleSel");if(n.type==="audio_gen")kill.push("#cvp_modeSel","#cvp_modelSel","#cvp_atChip","#cvp_atSep",".kf-area");if(n.type==="image_gen")kill.push("#cvp_modeSel",".kf-area");if(isKf)kill.push("#cvp_atChip","#cvp_atSep");kill.forEach(function(sel2){var el=card.querySelector(sel2);if(el)el.remove();});cvClampGear(n);if(n.type==="video_gen"||n.type==="image_gen"){var bar=card.querySelector(".bar");var sendRow=card.querySelector(".send-row");(sendRow||bar).insertAdjacentHTML("beforebegin",'<div class="seg" id="cvArsec"><button type="button" class="seg-cur">'+'<span class="seg-tx" id="cvArsecTx"></span><span class="seg-ar ic ic-chevron-down"></span></button></div>');var tx0=card.querySelector("#cvArsecTx");if(tx0)tx0.textContent=arsecLabel(n);}
var ed=card.querySelector("#cvp_prompt");if(ed){if(n.data.promptTokens&&n.data.promptTokens.length){cvReconstructFromTokens(ed,n.data.promptTokens,n.id);}else{ed.innerText=(n.type==="audio_gen")?(n.data.text||""):(n.data.prompt||"");}
ed.setAttribute("data-ph",(n.type==="audio_gen")?"输入要合成的文字":"描述你想要的画面…");}
var mmDef=MEDIA_MODES[n.type==="video_gen"?"video":"image"];if(mmDef){var mSel=card.querySelector("#cvp_modelSel select");if(mSel)mSel.innerHTML=(mmDef.models||[]).map(function(m){return'<option value="'+m.value+'">'+esc(m.text||m.value)+'</option>';}).join("");var mdSel=card.querySelector("#cvp_modeSel select");if(mdSel&&n.type==="video_gen")mdSel.innerHTML=(mmDef.modes||[]).map(function(m){return'<option value="'+m.value+'">'+esc(m.text||m.value)+'</option>';}).join("");if(n.type==="audio_gen"){var rsSel=card.querySelector("#cvp_audioRefSrcSel select");if(rsSel){if(!rsSel.options.length)rsSel.innerHTML='<option value="original">参考：原样本</option><option value="preview">参考：转换后</option>';var rv=n.data.refSource||"original";if(rsSel.querySelector('option[value="'+rv+'"]'))rsSel.value=rv;}
var rsWrap=card.querySelector("#cvp_audioRefSrcSel");if(rsWrap)rsWrap.style.display=n.data.voiceId?"":"none";}}
if(n.type==="video_gen"){var kfA=card.querySelector(".kf-area");var upA=card.querySelector(".up-area");var upI=card.querySelector("#cvp_upIconBtn");var atC=card.querySelector("#cvp_atChip");if(kfA)kfA.style.display=isKf?"flex":"none";if(upA)upA.style.display=isKf?"none":"flex";if(upI)upI.style.display=isKf?"none":"";if(atC)atC.style.display=isKf?"none":"";if(ed)ed.setAttribute("data-ph",isKf?"首尾帧控制：描述首帧到尾帧之间发生的动作与运镜，例如：人物缓缓转身走向窗边，镜头缓慢推进":"描述你想要的画面…");}
if(n.type==="image_gen"&&typeof IMAGE_STYLES!=="undefined"){var stSel=card.querySelector("#cvp_styleSel select");if(stSel){stSel.innerHTML=IMAGE_STYLES.map(function(s2){return'<option value="'+s2.v+'">'+esc(s2.n)+'</option>';}).join("");stSel.value=(n.data.style&&stSel.querySelector('option[value="'+n.data.style+'"]'))?n.data.style:"";}}
var setSel=function(selId,v,dft){var el=card.querySelector("#"+selId);if(!el||!el.options.length)return;var has=function(x){return x!=null&&!!el.querySelector('option[value="'+x+'"]');};el.value=has(v)?v:(has(dft)?dft:el.options[0].value);};if(n.type==="video_gen"){var hasImg=inboundAssets(n.id).some(function(q){return q.kind==="image";});var dftMode=(mmDef&&mmDef.defaultMode)||"reference";setSel("cvp_mode",n.data.mode||(hasImg?"reference":dftMode),dftMode);setSel("cvp_model",n.data.model,"");}
if(n.type==="image_gen"){setSel("cvp_model",n.data.model,"");}
if(n.type==="audio_gen"){var spSel=card.querySelector("#cvp_audioSpeed");if(spSel){var spList=(typeof window.audioSpeedOptions==="function")?window.audioSpeedOptions():null;if(spList&&spList.length){spSel.innerHTML=spList.map(function(o){return'<option value="'+o.value+'">'+esc(o.text)+"</option>";}).join("");}else{var spOpts=[];for(var sv=0.25;sv<=4.0+1e-9;sv=Math.round((sv+0.25)*100)/100){spOpts.push('<option value="'+sv+'">'+(Math.round(sv*100)/100)+"×</option>");}
spSel.innerHTML=spOpts.join("");}
var curSp=String(n.data.speed||1);spSel.value=spSel.querySelector('option[value="'+curSp+'"]')?curSp:"1";}}
card.querySelectorAll("#cvp_modelSel, #cvp_modeSel, #cvp_audioRefSrcSel").forEach(function(sg){var s2=sg.querySelector("select"),tx2=sg.querySelector(".seg-tx");if(s2&&tx2&&s2.options.length){var o2=s2.options[s2.selectedIndex];if(o2)tx2.textContent=o2.textContent;}});panel.appendChild(card);fillCvStrip(n,card);if(refLocked(n)){var lkd=document.createElement("div");lkd.className="cv-cap-hint";lkd.textContent=LOCKED_REF_MSG;card.appendChild(lkd);}
var oh=capOverHint(n);if(oh){var ohd=document.createElement("div");ohd.className="cv-cap-hint";ohd.textContent=oh;card.appendChild(ohd);}}else{panel.remove();return;}
var nodeEl=document.querySelector('[data-node="'+n.id+'"]');var nodeH=nodeEl?nodeEl.getBoundingClientRect().height/S.vp.zoom:n.h;panel.style.top=Math.round(n.y+nodeH+12)+"px";panel.style.maxWidth=Math.max(320,Math.round(window.innerWidth/S.vp.zoom-80))+"px";vp.appendChild(panel);panel.style.left=Math.round(n.x+n.w/2-panel.offsetWidth/2)+"px";var calibPanelPos=function(){var ne=document.querySelector('[data-node="'+n.id+'"]');if(!ne)return;panel.style.top=Math.round(n.y+ne.offsetHeight+12)+"px";panel.style.left=Math.round(n.x+n.w/2-panel.offsetWidth/2)+"px";};requestAnimationFrame(calibPanelPos);if(nodeEl)nodeEl.querySelectorAll("img").forEach(function(im){if(!im.complete)im.addEventListener("load",calibPanelPos,{once:true});});if(window.UISeg){panel.querySelectorAll(".seg[data-seg]").forEach(function(sg){if(!sg.querySelector(".seg-pop")){var baseWrap=document.getElementById(sg.id.replace(/^cvp_/,""));var basePopCls="seg-pop";if(baseWrap&&baseWrap._pop&&baseWrap._pop.className){basePopCls=baseWrap._pop.className.replace(/\b(show|open|up)\b/g,"").trim()||"seg-pop";}
sg.insertAdjacentHTML("beforeend",'<div class="'+esc(basePopCls)+'"></div>');}
var id=sg.id;var sel=sg.querySelector("select");if(sel&&sel.options.length)UISeg.init(id);});syncSegTexts(n);}
wirePanel(n);}
function syncSegTexts(n){if(!window.UISeg)return;if(n.type==="video_gen"){var mm=cardModelText(n.data.model);if(mm)UISeg.sync("cvp_modelSel",mm);}else if(n.type==="image_gen"){var mi=cardModelText(n.data.model);if(mi)UISeg.sync("cvp_modelSel",mi);}else if(n.type==="audio_gen"){UISeg.sync("cvp_audioSpeedSel",(n.data.speed||1)+"×");}}
function cardModelText(v){return v||"";}
function cvAudioLibText(panel,n){var tx=panel.querySelector("#cvp_audioLibSel .seg-tx");if(!tx)return;if(n.data.voiceId){tx.innerHTML='音色：'+esc(n.data.voiceName||"")+' <span class="cv-voice-x" title="清除音色">✕</span>';var x=tx.querySelector(".cv-voice-x");if(x)x.addEventListener("click",function(e){e.stopPropagation();n.data.voiceId="";n.data.voiceName="";n.data.voiceRef="";n.data.refSource="";var rs=panel.querySelector("#cvp_audioRefSrcSel");if(rs)rs.style.display="none";cvAudioLibText(panel,n);save();});}else{tx.textContent="音色库";}}
function inboundAssets(nid){return S.doc.edges.filter(function(e){return e.to===nid;}).map(function(e){var src=nodeById(e.from);if(!src||src.type!=="asset")return null;return{nodeId:src.id,edgeId:e.id,url:src.data.url,kind:src.data.kind,name:src.data.name};}).filter(Boolean);}
function inboundTexts(nid){return S.doc.edges.filter(function(e){return e.to===nid;}).map(function(e){var src=nodeById(e.from);return(src&&src.type==="txt")?(src.data.text||""):null;}).filter(Boolean);}
function wirePanel(n){var panel=document.getElementById("csStagePanel");console.log("[cv-wire] wirePanel 调用, type="+n.type);if(!panel)return;function save(){S.doc.name=S.doc.name;scheduleSave();}
var ed=panel.querySelector("#cvp_prompt");if(ed)ed.addEventListener("input",function(){var tx=cvInnerTextNoChips(ed);if(n.type==="audio_gen")n.data.text=tx;else n.data.prompt=tx;n.data.promptTokens=cvSerializeInput(ed);if(!ed.textContent.trim()&&/^<br\s*\/?>?$/i.test(ed.innerHTML.trim()))ed.innerHTML="";save();});var count=panel.querySelector("#csPvCount");if(count)count.addEventListener("change",function(){n.data.count=Math.max(1,parseInt(count.value,10)||1);save();});var speed=panel.querySelector("#csPvSpeed");if(speed)speed.addEventListener("change",function(){n.data.speed=parseFloat(speed.value)||1.0;save();});var atBtn=panel.querySelector("#cvp_atChip");if(atBtn)atBtn.addEventListener("click",function(e){e.stopPropagation();var edB=panel.querySelector("#cvp_prompt");if(edB){edB.focus();cvSaveCaret(edB);}
cvAtPop(edB?cvCaretAnchor(edB):atBtn.getBoundingClientRect(),n,{typed:false});});var upIcon=panel.querySelector("#cvp_upIconBtn");if(upIcon){upIcon.removeEventListener("click",upIcon._cvHandler||function(){});upIcon._cvHandler=function(e){e.stopPropagation();if(refLocked(n)){alert(LOCKED_REF_MSG);return;}
cvUpPop(upIcon,n);};upIcon.addEventListener("click",upIcon._cvHandler);}
var lib=panel.querySelector("#cvp_audioLibSel .seg-cur");if(lib){lib.addEventListener("click",function(e){e.stopPropagation();if(refLocked(n)){alert(LOCKED_REF_MSG);return;}
if(!window.AudioLib){alert("音色库组件未加载");return;}
window.AudioLib.open(lib,function(voice){n.data.voiceId=voice.id||"";n.data.voiceName=voice.name||"";n.data.voiceRef="";var rs=panel.querySelector("#cvp_audioRefSrcSel");if(rs)rs.style.display=n.data.voiceId?"":"none";cvAudioLibText(panel,n);save();});});cvAudioLibText(panel,n);}
var rsSeg2=panel.querySelector("#cvp_audioRefSrcSel");if(rsSeg2){var rsSel2=rsSeg2.querySelector("select");if(rsSel2)rsSel2.addEventListener("change",function(){n.data.refSource=rsSel2.value;if(window.audioSetRefSrc)window.audioSetRefSrc(rsSel2.value);save();});}
if(n.type==="video_gen"){[["#cvp_kfFirst","first"],["#cvp_kfLast","last"]].forEach(function(pair){var slot=panel.querySelector(pair[0]);if(!slot)return;var key=pair[1];var fillSlot=function(url){slot.classList.add("filled");var old=slot.querySelector("img");if(old)old.remove();var x0=slot.querySelector(".kf-x");if(x0)x0.remove();var img=document.createElement("img");img.alt="";img.src=_thumb(url,192);slot.appendChild(img);var xb=document.createElement("button");xb.className="kf-x";xb.title="移除";xb.innerHTML='<span class="ic ic-cancel"></span>';xb.addEventListener("click",function(ev){ev.stopPropagation();if(n.data.kf)n.data.kf[key]=null;slot.classList.remove("filled");img.remove();xb.remove();save();});slot.appendChild(xb);};if(n.data.kf&&n.data.kf[key]&&n.data.kf[key].url)fillSlot(n.data.kf[key].url);slot.addEventListener("click",function(e){if(e.target.closest(".kf-x"))return;if(refLocked(n)){alert(LOCKED_REF_MSG);return;}
var inp=document.createElement("input");inp.type="file";inp.accept="image/*,video/*";inp.style.display="none";document.body.appendChild(inp);inp.addEventListener("change",function(){var f=inp.files&&inp.files[0];if(!f)return;var fd=new FormData();fd.append("file",f);fetch(API+"/api/upload",{method:"POST",body:fd}).then(function(r){return r.json();}).then(function(j){if(!j.url)throw new Error(j.error||"上传失败");if(!n.data.kf)n.data.kf={};n.data.kf[key]={url:j.url,name:f.name};fillSlot(j.url);save();}).catch(function(e2){alert("首/尾帧上传失败："+(e2.message||e2));}).finally(function(){inp.remove();});});inp.click();});});}
[["cvp_modeSel",function(v){n.data.mode=v;}],["cvp_modelSel",function(v){n.data.model=v;}],["cvp_audioSpeedSel",function(v){n.data.speed=parseFloat(v)||1.0;}],["cvp_styleSel",function(v){n.data.style=v;}]].forEach(function(pair){var seg=panel.querySelector("#"+pair[0]);if(!seg)return;var sel=seg.querySelector("select");if(!sel)return;sel.addEventListener("change",function(){pair[1](sel.value);save();syncSegTexts(n);if(pair[0]==="cvp_modeSel"||pair[0]==="cvp_modelSel"){renderPanel();return;}
if(n.type==="image_gen"||n.type==="video_gen")renderNodesLight();});});var arsecBtn=panel.querySelector("#cvArsec .seg-cur");if(arsecBtn)arsecBtn.addEventListener("click",function(e){e.stopPropagation();openCvArsecPanel(arsecBtn,n);});var edAt=panel.querySelector("#cvp_prompt");if(edAt&&(n.type==="image_gen"||(n.type==="video_gen"&&n.data.mode!=="keyframe"))){["keyup","click","focus"].forEach(function(ev){edAt.addEventListener(ev,function(){cvSaveCaret(edAt);});});edAt.addEventListener("input",function(){cvOnPromptInput(edAt,n);});}
var gen=panel.querySelector("#cvp_send");console.log("[cv-wire] cvp_send ="+!!gen);if(gen){gen.dataset.cvBound="1";gen.addEventListener("click",function(){console.log("[cv-gen] send click 触发");startGenerate(n);});}
var view=panel.querySelector("#csPvView");if(view)view.addEventListener("click",function(){if(window.AL){window.AL.open();}});}
function renderNodesKeepSel(){var n=nodeById(S.sel);var focusId=null,pos=null;var ta=document.getElementById("csStagePanel");if(ta&&document.activeElement&&document.activeElement.id){focusId=document.activeElement.id;try{pos=document.activeElement.selectionStart;}catch(e){pos=null;}}
renderNodes();if(focusId){var el=document.getElementById(focusId);if(el){el.focus();try{if(pos!=null)el.setSelectionRange(pos,pos);}catch(e){}}}}
function openImageEditForNode(n){if(!window.IE||typeof window.IE.open!=="function"){alert("图片编辑组件未加载");return;}
var bridge=window.IEBridge||{};var origGo=bridge.goImage,origPush=bridge.pushUserMsg;var consumed=false;var restore=function(){if(consumed)return;consumed=true;if(origGo)bridge.goImage=origGo;if(origPush)bridge.pushUserMsg=origPush;};bridge.pushUserMsg=function(){return null;};bridge.goImage=function(payload){restore();var src=n.data.url;var gen=addNode("image_gen",n.x+n.w+60,n.y);gen.data={prompt:payload.prompt||"",model:payload.model||"",size:payload.size||"1K",ratio:payload.ratio||"1:1",count:1};S.doc.edges.push({id:"e_"+Date.now().toString(36)+Math.random().toString(36).slice(2,5),from:n.id,to:gen.id,kind:"asset_ref"});S.sel=gen.id;saveNow();renderNodes();renderEdges();startGenerate(gen);};try{window.IE.open(n.data.url,n.data.name||"图片编辑");}
catch(e){restore();alert("打开图片编辑失败："+e.message);}
var watch=setInterval(function(){var mask=document.getElementById("ieMask");if(!mask||!mask.classList.contains("show")){restore();clearInterval(watch);}},600);}
function cvRefSlots(nid){var caps=nodeCaps(nodeById(nid)||{data:{}});var capImg=caps.image,capAud=caps.audio,capVid=caps.video;var q=inboundAssets(nid);var images=[],audios=[],videos=[],numOf={},tagOf={};var over={image:0,audio:0,video:0};var capOf={image:capImg,audio:capAud,video:capVid};var arrOf={image:images,audio:audios,video:videos};var CN={image:"Picture",audio:"Audio",video:"Video"};var CNtag={image:"图",audio:"音",video:"视"};q.forEach(function(a){var arr=arrOf[a.kind];if(!arr||!a.url)return;var cap=capOf[a.kind];if(arr.length>=cap){over[a.kind]++;return;}
arr.push(a.url);numOf[a.url]=arr.length;tagOf[a.url]=CNtag[a.kind]+arr.length;});return{images:images,audios:audios,videos:videos,numOf:numOf,tagOf:tagOf,over:over,CN:CN,queue:q};}
function cvAssetUrlByNum(nid,kind,num){var s=cvRefSlots(nid);var arr=kind==="audio"?s.audios:(kind==="video"?s.videos:s.images);var u=arr[num-1];return u||null;}
function cvBuildRefData(n,ed){var slots=cvRefSlots(n.id);var images=slots.images,audios=slots.audios,videos=slots.videos;var numOf=slots.numOf;var CN=slots.CN;var text="";if(ed){var seen={};(function walk(node){node.childNodes.forEach(function(ch){if(ch.nodeType===3){text+=ch.textContent;return;}
if(ch.nodeType!==1||!ch.classList)return;if(ch.classList.contains("in-asset")){var u=ch.dataset.url||"";var kind2=ch.classList.contains("audio-asset")?"audio":(ch.classList.contains("video-asset")?"video":"image");var N=numOf[u];if(!N)return;if(!seen[kind2+u]){seen[kind2+u]=true;text+="<"+CN[kind2]+" "+N+">";}
return;}
if(ch.tagName==="BR"){text+="\n";return;}
walk(ch);});})(ed);}
if(!text.trim())text=(n.type==="audio_gen")?(n.data.text||""):(n.data.prompt||"");text=text.replace(/图\s*(\d+)/g,function(m0,n1){var u=cvAssetUrlByNum(n.id,"image",+n1);var N=u?numOf[u]:0;return N?"<"+CN.image+" "+N+">":m0;}).replace(/音\s*(\d+)/g,function(m0,n1){var u=cvAssetUrlByNum(n.id,"audio",+n1);var N=u?numOf[u]:0;return N?"<"+CN.audio+" "+N+">":m0;}).replace(/视\s*(\d+)/g,function(m0,n1){var u=cvAssetUrlByNum(n.id,"video",+n1);var N=u?numOf[u]:0;return N?"<"+CN.video+" "+N+">":m0;});text=text.replace(/[ \t]+\n/g,"\n").replace(/\n{3,}/g,"\n\n").trim();[["Picture",images],["Audio",audios],["Video",videos]].forEach(function(p){var kind=p[0].toLowerCase();var used=p[1].filter(function(u){return text.indexOf("<"+p[0]+" "+numOf[u]+">")>=0;}).length;if(p[1].length&&!used)
console.warn("[canvas] 有 "+p[1].length+" 个"+CN[kind]+"素材已随请求发出，但提示词未出现任何 <"+p[0]+" N> 引用");});return{prompt:text,images:images,audios:audios,videos:videos};}
function startGenerate(n){console.log("[cv-gen] startGenerate 进入, type="+n.type+", status="+n.data.status);if(n.data.status==="processing")return;var queue=inboundAssets(n.id);var extraPrompt="";if(n.type==="image_gen"){var refData=cvBuildRefData(n,document.getElementById("cvp_prompt"));var imgs=refData.images;var prompt=[refData.prompt,extraPrompt].filter(Boolean).join("\n");if(!prompt){alert("先在面板里填提示词");return;}
if(typeof styleDef==="function"){var stD=styleDef(n.data.style);if(stD&&stD.p)prompt=prompt+"，"+stD.p;}
n.data.status="processing";n.data.error=null;renderNodes();fetch(API+"/api/image/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:n.data.model||undefined,prompt:prompt,images:imgs,size:n.data.size||"1K",ratio:n.data.ratio||"1:1",count:n.data.count||1,seed:n.data.seed||undefined})}).then(function(r){return r.json().then(function(j){return{ok:r.ok,j:j};});}).then(function(res){if(!res.ok||!res.j.task_id)throw new Error(res.j.error||"提交失败");n.data.task_ref=res.j.task_id;saveNow();startPoll(n.id,res.j.task_id);}).catch(function(e){n.data.status="error";n.data.error=e.message;saveNow();renderNodes();});}else if(n.type==="video_gen"){var isKfGen=(n.data.mode==="keyframe");var refData=cvBuildRefData(n,document.getElementById("cvp_prompt"));var vi=isKfGen?[]:refData.images;var vaArr=isKfGen?[]:(refData.audios||[]);var vp2=[refData.prompt,extraPrompt].filter(Boolean).join("\n");if(!vp2){alert("先在面板里填提示词");console.log("[cv-gen] 视频提示词为空");return;}
n.data.status="processing";n.data.error=null;renderNodes();var _hasRef=vi.length||vaArr.length||(refData.videos&&refData.videos.length);var vPayload={model:n.data.model||undefined,prompt:vp2,mode:isKfGen?"keyframe":(_hasRef?"reference":"text"),images:vi,audios:isKfGen?undefined:(vaArr.length?vaArr:undefined),seconds:n.data.seconds||5,size:n.data.size||"720P",aspect_ratio:n.data.ratio||"16:9",seed:n.data.seed||undefined};if(!isKfGen&&refData.videos.length)vPayload.videos=refData.videos;if(isKfGen){if(n.data.kf&&n.data.kf.first&&n.data.kf.first.url)vPayload.first_frame=n.data.kf.first.url;if(n.data.kf&&n.data.kf.last&&n.data.kf.last.url)vPayload.last_frame=n.data.kf.last.url;}
fetch(API+"/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(vPayload)}).then(function(r){return r.json().then(function(j){return{ok:r.ok,j:j};});}).then(function(res){var tid=res.j.video_id||res.j.task_id;if(!res.ok||!tid)throw new Error(res.j.error||"提交失败");n.data.task_ref=tid;saveNow();startPoll(n.id,tid,n.data.model);}).catch(function(e){n.data.status="error";n.data.error=e.message;saveNow();renderNodes();});}else if(n.type==="audio_gen"){var txt=[n.data.text,extraPrompt].filter(Boolean).join("\n");if(!txt){alert("先填朗读文本");return;}
var voiceId=n.data.voiceId||"";var audioQueue=queue.filter(function(q){return q.kind==="audio";});var refUrl=(!voiceId&&(audioQueue.length?(audioQueue[0].url||""):(n.data.voiceRef||"")))||"";var refName=n.data.voiceName||(audioQueue.length?(audioQueue[0].name||""):"")||"参考音色";n.data.status="processing";n.data.error=null;renderNodes();var submitTts=function(reference_audio){var body={text:txt,speed:n.data.speed||1.0,count:n.data.count||2};if(voiceId){body.voice_id=voiceId;body.ref_source=n.data.refSource||"original";}else if(reference_audio){body.reference_audio=reference_audio;body.voice_name=refName;}
fetch(API+"/api/tts/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}).then(function(r){return r.json().then(function(j){return{ok:r.ok,j:j};});}).then(function(res){if(!res.ok||!res.j.job||!res.j.job.id)throw new Error(res.j.error||"提交失败");n.data.task_ref=res.j.job.id;saveNow();startTtsPoll(n.id,res.j.job.id);}).catch(function(e){n.data.status="error";n.data.error=e.message;saveNow();renderNodes();});};if(refUrl){fetch(refUrl,{cache:"no-store"}).then(function(r){if(!r.ok)throw new Error("参考音频读取失败（HTTP "+r.status+"）");return r.blob();}).then(function(blob){return new Promise(function(res,rej){var fr=new FileReader();fr.onload=function(){res(fr.result);};fr.onerror=function(){rej(new Error("读取参考音频失败"));};fr.readAsDataURL(blob);});}).then(function(dataUrl){submitTts(dataUrl);}).catch(function(e){n.data.status="error";n.data.error=e.message;saveNow();renderNodes();});}else{submitTts("");}}}
function startPoll(nid,tid,model){stopPoll(nid);var isImg=(nodeById(nid)||{}).type==="image_gen";var pollOnce=function(){var n=nodeById(nid);if(!n){stopPoll(nid);return;}
var url=isImg?API+"/api/task/"+encodeURIComponent(tid):API+"/api/status?video_id="+encodeURIComponent(tid)+"&model_name="+encodeURIComponent(model||n.data.model||"");fetch(url).then(function(r){return r.json().then(function(j){return{ok:r.ok,j:j};});}).then(function(res){var j=res.j||{};if(!res.ok&&!j.status){n.data.status="error";n.data.error=j.error||("查询失败（HTTP "+res.ok+"）");stopPoll(nid);saveNow();renderNodes();return;}
if(j.status==="completed"||j.status==="success"||j.status==="done"){n.data.status="done";n.data.result=j.image_urls||(j.video_url?[j.video_url]:[]);stopPoll(nid);saveNow();renderNodes();}else if(j.status==="failed"||j.status==="error"){n.data.status="error";n.data.error=j.error||"生成失败";stopPoll(nid);saveNow();renderNodes();}}).catch(function(e){n.data.status="error";n.data.error="查询失败："+((e&&e.message)||"网络异常");stopPoll(nid);saveNow();renderNodes();});};pollOnce();S.polls[nid]=setInterval(pollOnce,3000);}
function stopPoll(nid){if(S.polls[nid]){clearInterval(S.polls[nid]);delete S.polls[nid];}}
function startTtsPoll(nid,jid){stopPoll(nid);var pollOnce=function(){var n=nodeById(nid);if(!n){stopPoll(nid);return;}
fetch(API+"/api/tts/job/"+encodeURIComponent(jid)).then(function(r){return r.json();}).then(function(j){if(!j||!j.job)return;var job=j.job,st=job.status;if(st==="completed"){var cands=(job.candidates||[]).filter(Boolean).map(function(c){if(typeof c==="string")return c;return c.url||("/api/tts/file/"+(c.path||""));}).filter(Boolean);n.data.status=cands.length?"done":"error";n.data.result=cands.slice(0,2);if(!cands.length)n.data.error=(job.errors&&job.errors[0])||"合成返回为空";stopPoll(nid);saveNow();renderNodes();}else if(st==="failed"){n.data.status="error";n.data.error=(job.errors&&job.errors[0])||"合成失败";stopPoll(nid);saveNow();renderNodes();}}).catch(function(){});};pollOnce();S.polls[nid]=setInterval(pollOnce,3000);}
function scheduleSave(){var el=document.getElementById("csSave");if(el){el.textContent="… 保存中";el.className="save saving";}
if(S.saveTimer)clearTimeout(S.saveTimer);S.saveTimer=setTimeout(saveNow,700);}
function saveNow(){if(!S.doc)return;S.doc.viewport=S.vp;var el=document.getElementById("csSave");fetch(API+"/api/canvas/projects/"+S.doc.id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(S.doc)}).then(function(){if(el){el.textContent="✓ 已保存";el.className="save";}}).catch(function(){if(el){el.textContent="⚠ 保存失败";el.className="save saving";}});}
function fitNodeMedia(el){var nodeEl=el.closest(".cs-node");if(!nodeEl)return;var n=nodeById(nodeEl.getAttribute("data-node"));if(!n)return;var rw=el.naturalWidth||el.videoWidth,rh=el.naturalHeight||el.videoHeight;if(!rw||!rh)return;var ratio=rw/rh;var target=(el.tagName==="VIDEO")?280:Math.round(110*ratio);var w=Math.max(120,Math.min(320,target));if(Math.abs(w-n.w)<=4){renderEdges();return;}
n.w=w;saveNow();renderNodes();renderEdges();if(S.sel===n.id)renderPanel();}
function wireWork(){var work=document.getElementById("csWork");if(!work||work.dataset.csWired==="1")return;work.dataset.csWired="1";var pan=null,drag=null;var link=S.linking;work.addEventListener("load",function(e){if(e.target&&e.target.matches&&e.target.matches(".nd-thumb"))fitNodeMedia(e.target);},true);work.addEventListener("loadedmetadata",function(e){if(e.target&&e.target.matches&&e.target.matches(".nd-thumb"))fitNodeMedia(e.target);},true);var stage=document.getElementById("canvasStage");if(stage&&stage.dataset.csDrop!=="1"){stage.dataset.csDrop="1";stage.addEventListener("dragover",function(e){e.preventDefault();if(e.dataTransfer)e.dataTransfer.dropEffect="copy";});stage.addEventListener("drop",function(e){e.preventDefault();var fs2=e.dataTransfer&&e.dataTransfer.files;if(!fs2||!fs2.length)return;var rect=work.getBoundingClientRect();var inside=e.clientX>=rect.left&&e.clientX<=rect.right&&e.clientY>=rect.top&&e.clientY<=rect.bottom;var wx=inside?(e.clientX-rect.left-S.vp.x)/S.vp.zoom:(rect.width/2-S.vp.x)/S.vp.zoom;var wy=inside?(e.clientY-rect.top-S.vp.y)/S.vp.zoom:(rect.height/2-S.vp.y)/S.vp.zoom;dropUploadFiles(fs2,wx,wy);});}
work.addEventListener("mousedown",function(e){if(e.button!==0)return;if(e.target.closest(".cs-menu, .cs-bottom, .cs-top, .at-pop, .kf-pop"))return;var pnl=e.target.closest(".cs-panel");if(pnl&&e.target.closest("button,input,textarea,select,.editable,.seg,.send-row,.upload-strip,.uth,.kf-slot,.in-asset,.at-pop,input,video,audio"))return;if(window.Timeline&&window.Timeline.capture(e))return;var nodeEl=e.target.closest(".cs-node");var head=e.target.closest(".nd-head");var port=e.target.closest(".cs-port");var rsz=e.target.closest(".rsz");if(rsz){var rn=nodeById(rsz.getAttribute("data-rsz"));if(rn)drag={type:"resize",n:rn,sx:e.clientX,sy:e.clientY,w0:rn.w,h0:rn.h};e.preventDefault();return;}
if(port&&port.getAttribute("data-pout")){var fn=nodeById(port.getAttribute("data-pout"));if(fn){var pp=portPos(fn,"out");S.linking={from:fn.id,x:pp.x,y:pp.y};}
e.preventDefault();return;}
if(nodeEl){if(e.target.tagName==="TEXTAREA"||e.target.tagName==="INPUT")return;var nid=nodeEl.getAttribute("data-node");select(nid,{additive:e.ctrlKey||e.metaKey,range:e.shiftKey});var n2=nodeById(nid);if(n2){S._dragSnap=snapshotDoc();drag={type:"move",n:n2,sx:e.clientX,sy:e.clientY,x0:n2.x,y0:n2.y,moved:false,group:(S.selSet||[]).map(function(id){var gn=nodeById(id);return gn?{n:gn,x0:gn.x,y0:gn.y}:null;}).filter(Boolean)};}
e.preventDefault();return;}
var edel=e.target.closest("[data-edel]");if(edel){var delId=edel.getAttribute("data-edel");pushHistory(snapshotDoc());S.doc.edges=S.doc.edges.filter(function(x){return x.id!==delId;});S.edgeSel=null;saveNow();renderEdges();e.preventDefault();return;}
var edge=e.target.closest("[data-edge]");if(edge){S.edgeSel=edge.getAttribute("data-edge");renderEdges();e.preventDefault();return;}
if(S.edgeSel){S.edgeSel=null;renderEdges();}
if(e.altKey){pan={sx:e.clientX,sy:e.clientY,x0:S.vp.x,y0:S.vp.y};}else{S.marquee={sx:e.clientX,sy:e.clientY,add:e.ctrlKey||e.metaKey,base:(S.selSet||[]).slice()};var mq=document.createElement("div");mq.className="cs-marquee";mq.id="csMarquee";mq.style.left=S.marquee.sx+"px";mq.style.top=S.marquee.sy+"px";mq.style.width="0px";mq.style.height="0px";work.appendChild(mq);}});document.addEventListener("mousemove",function(e){if(!S.marquee)return;var mq=document.getElementById("csMarquee");if(!mq)return;var wr=document.getElementById("csWork").getBoundingClientRect();var x=Math.max(wr.left,Math.min(wr.right,e.clientX));var y=Math.max(wr.top,Math.min(wr.bottom,e.clientY));mq.style.left=Math.min(S.marquee.sx,x)+"px";mq.style.top=Math.min(S.marquee.sy,y)+"px";mq.style.width=Math.abs(x-S.marquee.sx)+"px";mq.style.height=Math.abs(y-S.marquee.sy)+"px";});work.addEventListener("mousemove",function(e){if(pan){S.vp.x=pan.x0+(e.clientX-pan.sx);S.vp.y=pan.y0+(e.clientY-pan.sy);applyViewport();return;}
if(drag){var dx=(e.clientX-drag.sx)/S.vp.zoom,dy=(e.clientY-drag.sy)/S.vp.zoom;if(drag.type==="move"){if(drag.group&&drag.group.length){drag.group.forEach(function(g){g.n.x=Math.round(g.x0+dx);g.n.y=Math.round(g.y0+dy);});drag.n=drag.group[0].n;}else{drag.n.x=Math.round(drag.x0+dx);drag.n.y=Math.round(drag.y0+dy);}
drag.moved=true;computeSnap(drag.n);renderNodesLight();renderEdges();}else if(drag.type==="resize"){drag.n.w=Math.max(120,Math.round(drag.w0+dx));drag.n.h=Math.max(70,Math.round(drag.h0+dy));renderNodesLight();renderEdges();}
return;}
if(S.linking){if(S.linking.frozen)return;var rect=work.getBoundingClientRect();S.linking.mx=(e.clientX-rect.left-S.vp.x)/S.vp.zoom;S.linking.my=(e.clientY-rect.top-S.vp.y)/S.vp.zoom;drawLinkGhost();}});document.addEventListener("mouseup",function(e){if(S.marquee){finishMarquee(e.clientX,e.clientY);return;}});work.addEventListener("mouseup",function(e){if(drag){if(drag.moved||drag.type==="resize"){if(S._dragSnap)pushHistory(S._dragSnap);saveNow();renderPanel();}
clearGuides();S._dragSnap=null;drag=null;}
if(pan){pan=null;scheduleSave();}
if(S.linking){var link=S.linking;var port=e.target.closest(".cs-port");var hitNode=e.target.closest(".cs-node");var toId=null;if(port&&port.getAttribute("data-pin"))toId=port.getAttribute("data-pin");else if(hitNode){var hn=nodeById(hitNode.getAttribute("data-node"));if(hn&&hn.id!==link.from&&NODE_DEFS[hn.type]&&NODE_DEFS[hn.type].ports&&NODE_DEFS[hn.type].ports.in)toId=hn.id;}
var okDone=false;if(toId){var to=nodeById(toId);var from=nodeById(link.from);var isTl=!!(to&&to.type==="timeline"&&window.Timeline);if(isTl){var src=from.data||{};var url=(from.type==="asset")?src.url:((src.result&&src.result[0])||"");if(!url){alert("该节点还没有可加入时间线的素材");S.linking=null;removeLinkGhost();return;}
var kind=(from.type==="asset")?(src.kind||"image"):(from.type==="audio_gen"?"audio":(from.type==="video_gen"?"video":"image"));S.sel=to.id;saveNow();renderNodes();renderEdges();S.linking=null;removeLinkGhost();window.Timeline.acceptAsset(to.id,{url:url,kind:kind,name:src.name||"",edgeFrom:from.id});return;}
if(to&&from&&to.id!==from.id&&edgeAllowed(from,to)){var dup=S.doc.edges.some(function(x){return x.from===from.id&&x.to===to.id;});if(!dup){pushHistory(snapshotDoc());S.doc.edges.push({id:"e_"+Date.now().toString(36)+Math.random().toString(36).slice(2,5),from:from.id,to:to.id,kind:edgeKind(from,to)});if(from.type==="txt"&&from.data.text){var tx2=from.data.text;if(to.type==="audio_gen"){if((to.data.text||"").indexOf(tx2)<0)to.data.text=(to.data.text?to.data.text+"\n":"")+tx2;}else if((to.data.prompt||"").indexOf(tx2)<0){to.data.prompt=(to.data.prompt?to.data.prompt+"\n":"")+tx2;}}
S.sel=to.id;saveNow();renderNodes();renderEdges();okDone=true;}}else if(to&&from){alert(edgeReject(from,to)||"这种连线不符合画布规则");}}
if(!okDone){var from=nodeById(link.from);if(from){var workEl=document.getElementById("csWork");var r=workEl.getBoundingClientRect();S.linking.frozen=true;openMenu(e.clientX-r.left,e.clientY-r.top,link.mx,link.my,["library","upload"],link.from,function(){S.linking=null;removeLinkGhost();});}else{S.linking=null;removeLinkGhost();}}else{S.linking=null;}}});work.addEventListener("wheel",function(e){e.preventDefault();var rect=work.getBoundingClientRect();var mx=e.clientX-rect.left,my=e.clientY-rect.top;var factor=e.deltaY<0?1.12:1/1.12;var nz=Math.min(2.4,Math.max(0.35,S.vp.zoom*factor));var k=nz/S.vp.zoom;S.vp.x=mx-(mx-S.vp.x)*k;S.vp.y=my-(my-S.vp.y)*k;S.vp.zoom=nz;applyViewport();renderEdges();scheduleSave();},{passive:false});work.addEventListener("dblclick",function(e){if(e.target.closest(".cs-node, .cs-menu, .cs-panel, .cs-bottom, textarea, input, [contenteditable='true'], [contenteditable='plaintext-only']"))return;var rect=work.getBoundingClientRect();var sx=e.clientX-rect.left,sy=e.clientY-rect.top;var wx=(sx-S.vp.x)/S.vp.zoom,wy=(sy-S.vp.y)/S.vp.zoom;openMenu(sx,sy,wx,wy);});work.addEventListener("contextmenu",function(e){e.preventDefault();openCtxMenu(e.clientX,e.clientY);});if(stage)stage.addEventListener("contextmenu",function(e){e.preventDefault();});bindTextHistory();work.addEventListener("input",function(e){var ta=e.target.closest("[data-txt]");if(ta){var n=nodeById(ta.getAttribute("data-txt"));if(n){n.data.text=ta.value;scheduleSave();}}});}
function select(nid,opts){opts=opts||{};if(!nid){S.sel=null;S.selSet=[];refreshSelUi();return;}
var i=S.selSet.indexOf(nid);if(opts.additive){if(i>=0)S.selSet.splice(i,1);else S.selSet.push(nid);if(S.selSet.indexOf(S.sel)<0)S.sel=S.selSet.length?S.selSet[S.selSet.length-1]:null;}else if(opts.range&&S.sel){var a=nodeById(S.sel),b=nodeById(nid);if(a&&b){var l=Math.min(a.x,b.x),t=Math.min(a.y,b.y),r=Math.max(a.x,b.x)+b.w,bo=Math.max(a.y,b.y)+b.h;var box=S.selSet.filter(function(id){return id!==nid&&id!==S.sel;});S.doc.nodes.forEach(function(n){var el=document.querySelector('[data-node="'+n.id+'"]');if(!el)return;if(n.x+el.offsetWidth>=l&&n.x<=r&&n.y+el.offsetHeight>=t&&n.y<=bo)box.push(n.id);});S.selSet=box;if(S.selSet.indexOf(nid)<0)S.selSet.push(nid);S.sel=nid;}else{S.sel=nid;}}else{S.sel=nid;S.selSet=[nid];}
if(S.sel&&S.selSet.length>1&&S.selSet.indexOf(S.sel)<0)S.sel=S.selSet[0];refreshSelUi();}
function finishMarquee(cx,cy){var mq=document.getElementById("csMarquee");if(mq)mq.remove();var st=S.marquee;S.marquee=null;if(!st)return;var workRect=document.getElementById("csWork").getBoundingClientRect();var x0=Math.min(st.sx,cx)-workRect.left,y0=Math.min(st.sy,cy)-workRect.top;var x1=Math.max(st.sx,cx)-workRect.left,y1=Math.max(st.sy,cy)-workRect.top;if((x1-x0)<=6&&(y1-y0)<=6){if(!st.add){S.selSet=[];S.sel=null;}
refreshSelUi();return;}
var wl=(x0-S.vp.x)/S.vp.zoom,wt=(y0-S.vp.y)/S.vp.zoom;var wr=(x1-S.vp.x)/S.vp.zoom,wb=(y1-S.vp.y)/S.vp.zoom;var picked=st.add?(st.base||[]).slice():[];S.doc.nodes.forEach(function(n){if(picked.indexOf(n.id)>=0)return;var el=document.querySelector('[data-node="'+n.id+'"]');var nh=Math.max(n.h||0,el?(el.offsetHeight||0):0);if(n.x+n.w>=wl&&n.x<=wr&&n.y+nh>=wt&&n.y<=wb)picked.push(n.id);});S.selSet=picked;S.sel=picked.length?picked[picked.length-1]:null;refreshSelUi();}
function refreshSelUi(){document.querySelectorAll("#csNodes .cs-node").forEach(function(el){var id=el.getAttribute("data-node");el.classList.toggle("sel",id===S.sel||(S.selSet||[]).indexOf(id)>=0);});renderEdges();renderPanel();}
function deleteNodes(ids){if(!ids.length)return;if(!confirm("确定删除选中的 "+ids.length+" 个节点？相关的素材可在资产库中查看。"))return;if(window.Timeline)ids.forEach(function(id){var n=nodeById(id);if(n)window.Timeline.dispose(n);});pushHistory(snapshotDoc());S.doc.nodes=S.doc.nodes.filter(function(n){return ids.indexOf(n.id)<0;});S.doc.edges=S.doc.edges.filter(function(e){return ids.indexOf(e.from)<0&&ids.indexOf(e.to)<0;});if(ids.indexOf(S.sel)>=0)S.sel=null;S.selSet=[];saveNow();renderNodes();renderEdges();}
function renderNodesLight(){S.doc.nodes.forEach(function(n){var el=document.querySelector('[data-node="'+n.id+'"]');if(el){el.style.left=n.x+"px";el.style.top=n.y+"px";el.style.width=n.w+"px";if(n.type==="txt")el.style.height=n.h+"px";}});}
function openMenu(sx,sy,wx,wy,exclude,fromId,onCancel){closeMenu();var sel=window.getSelection&&window.getSelection();if(sel&&sel.removeAllRanges)sel.removeAllRanges();var work=document.getElementById("csWork");var m=document.createElement("div");m.className="cs-menu";m.id="csMenu";m.style.left=sx+"px";m.style.top=sy+"px";m.innerHTML=createMenuHtml(exclude);work.appendChild(m);m.addEventListener("click",function(e){var b=e.target.closest("[data-mk]");if(!b)return;var kind=b.getAttribute("data-mk");closeMenu();createMenuClick(kind,wx,wy,fromId);});function closeMenuOnce(e){if(e.target.closest("#csMenu"))return;closeMenu();if(onCancel)onCancel();}
setTimeout(function(){document.addEventListener("click",closeMenuOnce,{once:true});},0);}
function closeMenu(){var m=document.getElementById("csMenu");if(m)m.remove();}
function deepClone(o){return(o==null||typeof o!=="object")?o:JSON.parse(JSON.stringify(o));}
function newId(p){return p+"_"+Date.now().toString(36)+Math.random().toString(36).slice(2,5);}
function snapshotDoc(){var st={nodes:deepClone(S.doc.nodes),edges:deepClone(S.doc.edges)};if(window.Timeline){st.nodes.forEach(function(n){if(n&&n.data&&n.data.tl)delete n.data.tl.ui;});}
return st;}
function applyDoc(st){var savedUi={};if(window.Timeline){(S.doc.nodes||[]).forEach(function(n){if(n&&n.data&&n.data.tl&&n.data.tl.ui)savedUi[n.id]=n.data.tl.ui;});}
S.doc.nodes=deepClone(st.nodes);S.doc.edges=deepClone(st.edges);if(window.Timeline)window.Timeline.restoreUi(S.doc.nodes,savedUi);S.sel=null;S.selSet=[];S.edgeSel=null;saveNow();renderNodes();renderEdges();refreshSelUi();if(window.Timeline&&window.Timeline.render)window.Timeline.render();renderEdges();}
function pushHistory(prev){if(!prev)return;S.undoStack.push(prev);if(S.undoStack.length>200)S.undoStack.shift();S.redoStack=[];}
function undo(){if(!S.undoStack.length)return;S.redoStack.push(snapshotDoc());applyDoc(S.undoStack.pop());}
function redo(){if(!S.redoStack.length)return;S.undoStack.push(snapshotDoc());applyDoc(S.redoStack.pop());}
function curSel(nid){var ss=S.selSet||[];if(ss.length&&(!nid||ss.indexOf(nid)>=0))return ss.slice();return nid?[nid]:[];}
function copyNodes(ids){var picked=[],seen={};(ids||[]).forEach(function(id){if(!seen[id]&&nodeById(id)){seen[id]=1;picked.push(id);}});if(!picked.length)return;var extra={},extraIds=[];S.doc.edges.forEach(function(e){if(!seen[e.to]||seen[e.from]||extra[e.from])return;var src=nodeById(e.from);if(!src||src.type!=="asset")return;extra[e.from]=1;extraIds.push(e.from);});var all=picked.concat(extraIds),idx={};all.forEach(function(id,i){idx[id]=i;});var nodes=all.map(function(id){var n=nodeById(id);return{type:n.type,x:n.x,y:n.y,w:n.w,h:n.h,data:deepClone(n.data)};});var edges=S.doc.edges.filter(function(e){return idx[e.from]!=null&&idx[e.to]!=null;}).map(function(e){return{fi:idx[e.from],ti:idx[e.to],kind:e.kind};});var ps=picked.map(function(id){return nodeById(id);});S.clipboard={nodes:nodes,edges:edges,ax:Math.min.apply(null,ps.map(function(n){return n.x;})),ay:Math.min.apply(null,ps.map(function(n){return n.y;}))};}
function pasteNodes(wx,wy){var c=S.clipboard;if(!c||!c.nodes||!c.nodes.length)return;var x0=(wx!=null)?wx:c.ax+30;var y0=(wy!=null)?wy:c.ay+30;var dx=Math.round(x0-c.ax),dy=Math.round(y0-c.ay);pushHistory(snapshotDoc());var made=[];c.nodes.forEach(function(t){var n={id:newId("n"),type:t.type,x:t.x+dx,y:t.y+dy,w:t.w,h:t.h,data:deepClone(t.data)};if(n.type==="image_gen"||n.type==="video_gen"||n.type==="audio_gen"){delete n.data.status;delete n.data.result;delete n.data.task_ref;delete n.data.error;}
S.doc.nodes.push(n);made.push(n);});c.edges.forEach(function(e){if(!made[e.fi]||!made[e.ti])return;S.doc.edges.push({id:newId("e"),from:made[e.fi].id,to:made[e.ti].id,kind:e.kind});});S.sel=made[0].id;S.selSet=made.length>1?made.map(function(n){return n.id;}):[];saveNow();renderNodes();renderEdges();refreshSelUi();}
function downloadNode(nid){var n=nodeById(nid);if(!n||!n.data||!n.data.url)return;window.open("/api/download?url="+encodeURIComponent(n.data.url),"_blank");}
function assetNodeWidth(kind){return kind==="video"?280:(kind==="audio"?250:NODE_DEFS.asset.w);}
function splitToAsset(nid){var n=nodeById(nid);if(!n)return;if(n.type==="asset"||n.type==="txt")return;if(!n.data||!n.data.result||!n.data.result.length)return;pushHistory(snapshotDoc());var kind=(n.type==="video_gen")?"video":(n.type==="audio_gen"?"audio":"image");var results=n.data.result.slice();var firstId=null;results.forEach(function(u,i){var id="n_"+Date.now().toString(36)+Math.random().toString(36).slice(2,5);if(!firstId)firstId=id;var fname=String(u).split("?")[0].split("/").pop();try{fname=decodeURIComponent(fname);}catch(e){}
var nm=(results.length>1&&n.data.name)?(n.data.name+" #"+(i+1)):(n.data.name||fname||(kind+" 素材"));S.doc.nodes.push({id:id,type:"asset",x:Math.round(n.x+n.w+60),y:Math.round(n.y+i*(n.h+24)),w:assetNodeWidth(kind),h:n.h,data:{kind:kind,url:u,name:nm}});});if(firstId){S.doc.edges.forEach(function(e){if(e.from===n.id)e.from=firstId;});S.sel=firstId;}
saveNow();renderNodes();renderEdges();}
var CREATE_ITEMS=[["txt","ic-pencil","文本"],["image_gen","ic-image","图片生成"],["video_gen","ic-vgen","视频生成"],["audio_gen","ic-audio","音频生成"],["timeline","ic-vcompose","视频合成"],["library","ic-library","资产库"],["upload","ic-upload","本地上传"]];function createMenuHtml(exclude){var skip=exclude||[];var mk=function(list){return list.map(function(it){if(skip.indexOf(it[0])>=0)return"";return'<button data-mk="'+it[0]+'"><span class="ic '+it[1]+'"></span>'+it[2]+'</button>';}).join("");};var top=mk(CREATE_ITEMS.slice(0,5));var bottom=mk(CREATE_ITEMS.slice(5));if(!top)return bottom;if(!bottom)return top;return top+'<div class="cs-menu-sep"></div>'+bottom;}
function cleanupLinkMenu(){if(S.linking&&S.linking.frozen){S.linking=null;removeLinkGhost();}}
function createMenuClick(kind,wx,wy,fromId){if(kind==="upload"){uploadAsset(wx,wy);cleanupLinkMenu();return;}
if(kind==="library"){pickAsset(wx,wy);cleanupLinkMenu();return;}
var n=addNode(kind,wx,wy);if(fromId){var from=nodeById(fromId);if(from&&from.id!==n.id&&edgeAllowed(from,n)){S.doc.edges.push({id:"e_"+Date.now().toString(36)+Math.random().toString(36).slice(2,5),from:from.id,to:n.id,kind:edgeKind(from,n)});if(from.type==="txt"&&from.data.text){var tx2=from.data.text;if(n.type==="audio_gen"){if((n.data.text||"").indexOf(tx2)<0)n.data.text=(n.data.text?n.data.text+"\n":"")+tx2;}else if((n.data.prompt||"").indexOf(tx2)<0){n.data.prompt=(n.data.prompt?n.data.prompt+"\n":"")+tx2;}}
saveNow();renderNodes();renderEdges();cleanupLinkMenu();return;}}
saveNow();renderNodes();renderEdges();cleanupLinkMenu();}
var _subHideTimer=null;function scheduleSubHide(){_subHideTimer=setTimeout(closeCreateSub,280);}
function cancelSubHide(){if(_subHideTimer){clearTimeout(_subHideTimer);_subHideTimer=null;}}
function closeCreateSub(){var s=document.getElementById("csCreateMenu");if(s)s.remove();cancelSubHide();}
function openCreateMenu(x,y,wx,wy,exclude){closeCreateSub();var m=document.createElement("div");m.className="cs-menu cs-create";m.id="csCreateMenu";m.style.left=x+"px";m.style.top=y+"px";m.innerHTML=createMenuHtml(exclude);document.getElementById("csWork").appendChild(m);m.addEventListener("mouseenter",cancelSubHide);m.addEventListener("mouseleave",scheduleSubHide);m.addEventListener("click",function(e){var b=e.target.closest("[data-mk]");if(!b)return;var kind=b.getAttribute("data-mk");closeCtxMenu();createMenuClick(kind,wx,wy);});}
function closeCtxMenu(){var m=document.getElementById("csCtx");if(m)m.remove();closeCreateSub();}
function openCtxMenu(cx,cy){document.removeEventListener("mousedown",ctxCloser,true);closeCtxMenu();var work=document.getElementById("csWork");var rect=work.getBoundingClientRect();var sx=cx-rect.left,sy=cy-rect.top;var wx=(sx-S.vp.x)/S.vp.zoom,wy=(sy-S.vp.y)/S.vp.zoom;var tgt=document.elementFromPoint(cx,cy);var nodeEl=tgt&&tgt.closest?tgt.closest(".cs-node"):null;var nid=nodeEl?nodeEl.getAttribute("data-node"):null;var n=nid?nodeById(nid):null;if(nid){if((S.selSet||[]).indexOf(nid)>=0){S.sel=nid;refreshSelUi();}
else select(nid);}
var isAsset=!!(n&&n.type==="asset");var isEmpty=!n;var isGen=!!n&&(n.type==="image_gen"||n.type==="video_gen"||n.type==="audio_gen");var hasResult=!!(n&&n.data&&n.data.result&&n.data.result.length);var m=document.createElement("div");m.className="cs-menu cs-ctx";m.id="csCtx";m.style.left=sx+"px";m.style.top=sy+"px";var actIds=curSel(nid);var selCount=actIds.length;var nSel=selCount||0;var items=[];if(isEmpty){items.push({act:"new",ic:"ic-plus",txt:"新建节点",arrow:true});}
items.push({act:"copy",ic:"ic-copy",txt:nSel>1?"复制 "+nSel+" 个节点":"复制节点",kbd:"Ctrl+C",disabled:isEmpty});items.push({act:"paste",ic:"ic-clipboard",txt:"粘贴节点",kbd:"Ctrl+V",disabled:!S.clipboard});if(isGen){items.push({act:"split",ic:"ic-split",txt:"拆分为素材",disabled:!hasResult});}
if(isAsset){items.push({act:"download",ic:"ic-download",txt:"下载"});}
if(!isEmpty){items.push({act:"del",ic:"ic-del",txt:nSel>1?"删除 "+nSel+" 个节点":"删除节点",kbd:"Del/⌫"});}
items.push({act:"tidy",ic:"ic-grid4",txt:"整理画布",disabled:!S.doc.nodes.length});items.push({sep:true});items.push({act:"undo",ic:"ic-undo",txt:"撤销",kbd:"Ctrl+Z",disabled:!S.undoStack.length});items.push({act:"redo",ic:"ic-redo",txt:"重做",kbd:"Ctrl+Shift+Z",disabled:!S.redoStack.length});m.innerHTML=items.map(function(it){if(it.sep)return'<div class="cs-menu-sep"></div>';var kbd=it.kbd?'<span class="cs-kbd">'+it.kbd+'</span>':'';var right=it.arrow?'<span class="ic ic-chevron-right cs-ctx-arrow"></span>':'';var cls=it.disabled?' disabled':'';return'<button data-ctx="'+it.act+'" class="'+cls+'"><span class="ic '+it.ic+'"></span>'+it.txt+kbd+right+'</button>';}).join("");work.appendChild(m);if(isEmpty){var newBtn=m.querySelector('[data-ctx="new"]');if(newBtn){newBtn.addEventListener("mouseenter",function(){cancelSubHide();var mr=m.getBoundingClientRect();openCreateMenu(mr.right-rect.left+6,mr.top-rect.top,wx,wy);});}}
m.addEventListener("mouseleave",scheduleSubHide);m.addEventListener("click",function(e){var b=e.target.closest("[data-ctx]");if(!b||b.classList.contains("disabled"))return;var act=b.getAttribute("data-ctx");if(act==="new")return;closeCtxMenu();if(act==="copy"){if(actIds.length)copyNodes(actIds);}
else if(act==="paste"){pasteNodes(wx,wy);}
else if(act==="download"){if(nid)downloadNode(nid);}
else if(act==="split"){if(nid)splitToAsset(nid);}
else if(act==="del"){if(actIds.length)deleteNodes(actIds);}
else if(act==="tidy"){tidyCanvas();}
else if(act==="undo"){undo();}
else if(act==="redo"){redo();}});setTimeout(function(){document.addEventListener("mousedown",ctxCloser,true);},0);}
function ctxCloser(e){if(e.target.closest("#csCtx")||e.target.closest("#csCreateMenu"))return;closeCtxMenu();document.removeEventListener("mousedown",ctxCloser,true);}
function openMenuAtBtn(btn){var work=document.getElementById("csWork");if(!work)return;var wr=work.getBoundingClientRect(),br=btn.getBoundingClientRect();var sx=Math.max(8,Math.min(br.left+br.width/2-wr.left-70,wr.width-148));var sy=Math.max(8,br.top-wr.top-235);var wx=(wr.width/2-S.vp.x)/S.vp.zoom,wy=(wr.height/2-S.vp.y)/S.vp.zoom;openMenu(sx,sy,wx,wy);}
function fitView(){var work=document.getElementById("csWork");if(!work||!S.doc||!S.doc.nodes.length)return;var minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;S.doc.nodes.forEach(function(n){var el=document.querySelector('[data-node="'+n.id+'"]');var w=el?el.offsetWidth:n.w,h=el?el.offsetHeight:n.h;if(n.x<minX)minX=n.x;if(n.y<minY)minY=n.y;if(n.x+w>maxX)maxX=n.x+w;if(n.y+h>maxY)maxY=n.y+h;});var pad=60,bw=maxX-minX,bh=maxY-minY;if(bw<=0||bh<=0)return;var z=Math.min((work.clientWidth-pad*2)/bw,(work.clientHeight-pad*2)/bh,1);z=Math.max(0.35,z);S.vp.zoom=z;S.vp.x=(work.clientWidth-bw*z)/2-minX*z;S.vp.y=(work.clientHeight-bh*z)/2-minY*z;applyViewport();renderEdges();scheduleSave();}
function snapThreshold(){return 6/(S.vp.zoom||1);}
function clearGuides(){var g=document.getElementById("csGuides");if(g)g.innerHTML="";}
function drawGuideSegV(x,y1,y2){var g=document.getElementById("csGuides");if(!g)return;g.innerHTML+='<line class="cs-guide" x1="'+x+'" y1="'+y1+'" x2="'+x+'" y2="'+y2+'"/>'
+'<circle class="cs-dot" cx="'+x+'" cy="'+y1+'" r="3"/>'
+'<circle class="cs-dot" cx="'+x+'" cy="'+y2+'" r="3"/>';}
function drawGuideSegH(y,x1,x2){var g=document.getElementById("csGuides");if(!g)return;g.innerHTML+='<line class="cs-guide" x1="'+x1+'" y1="'+y+'" x2="'+x2+'" y2="'+y+'"/>'
+'<circle class="cs-dot" cx="'+x1+'" cy="'+y+'" r="3"/>'
+'<circle class="cs-dot" cx="'+x2+'" cy="'+y+'" r="3"/>';}
function computeSnap(n){clearGuides();if(!S.snapEnabled)return;var th=snapThreshold();var PAD=6;var others=S.doc.nodes.filter(function(o){return o.id!==n.id;});var oi=others.map(function(o){var w=o.w||(NODE_DEFS[o.type]?NODE_DEFS[o.type].w:0);var h=o.h||(NODE_DEFS[o.type]?NODE_DEFS[o.type].h:0);return{node:o,w:w,h:h,v:[o.x,o.x+w/2,o.x+w],hr:[o.y,o.y+h/2,o.y+h]};});var nw=n.w||(NODE_DEFS[n.type]?NODE_DEFS[n.type].w:0);var nh=n.h||(NODE_DEFS[n.type]?NODE_DEFS[n.type].h:0);var dragV=[n.x,n.x+nw/2,n.x+nw];var dragH=[n.y,n.y+nh/2,n.y+nh];var bestV=null,bestH=null;dragV.forEach(function(dvx){oi.forEach(function(info){info.v.forEach(function(vx){var d=vx-dvx,ad=Math.abs(d);if(ad<=th&&(!bestV||ad<bestV.ad))bestV={ad:ad,d:d,x:vx,o:info};});});});dragH.forEach(function(dhy){oi.forEach(function(info){info.hr.forEach(function(hy){var d=hy-dhy,ad=Math.abs(d);if(ad<=th&&(!bestH||ad<bestH.ad))bestH={ad:ad,d:d,y:hy,o:info};});});});if(bestV){n.x+=bestV.d;var o=bestV.o.node,oh=bestV.o.h;var y1=Math.min(n.y,o.y)-PAD,y2=Math.max(n.y+nh,o.y+oh)+PAD;drawGuideSegV(bestV.x,y1,y2);}
if(bestH){n.y+=bestH.d;var o2=bestH.o.node,ow2=bestH.o.w;var x1=Math.min(n.x,o2.x)-PAD,x2=Math.max(n.x+nw,o2.x+ow2)+PAD;drawGuideSegH(bestH.y,x1,x2);}}
function tidyCanvas(){if(!S.doc.nodes.length)return;if(typeof dagre==="undefined"){if(typeof toast==="function")toast("布局库未加载");return;}
pushHistory(snapshotDoc());var GUT=56;var RGAP=140;var UGAP=96;var KIND_GAP=30;var GROUP_COLS=4;function isGen(n){return!!(n&&(n.type==="image_gen"||n.type==="video_gen"||n.type==="audio_gen"));}
function isTL(n){return!!(n&&n.type==="timeline");}
function isAsset(n){return!!(n&&n.type==="asset");}
function isInput(n){return!!(n&&(n.type==="asset"||n.type==="txt"));}
function realSize(n){var el=document.querySelector('[data-node="'+n.id+'"]');var w=(el&&el.offsetWidth)||n.w||(NODE_DEFS[n.type]?NODE_DEFS[n.type].w:160);var h=(el&&el.offsetHeight)||n.h||(NODE_DEFS[n.type]?NODE_DEFS[n.type].h:96);return{w:Math.round(w),h:Math.round(h)};}
function bboxOf(arr){var x0=1e9,y0=1e9,x1=-1e9,y1=-1e9;arr.forEach(function(n){x0=Math.min(x0,n.x);y0=Math.min(y0,n.y);x1=Math.max(x1,n.x+n.w);y1=Math.max(y1,n.y+n.h);});if(x1<x0)return{x:0,y:0,w:0,h:0};return{x:x0,y:y0,w:x1-x0,h:y1-y0};}
function placeByKind(assets,others,ox,oy,cols,kindGap){var order=["image","audio","video"],groups=[];order.forEach(function(k){var g=assets.filter(function(n){return(n.data&&n.data.kind)===k;});if(g.length)groups.push(g);});if(others&&others.length)groups.push(others);var cursorY=oy;groups.forEach(function(grp,gi){var mw=0,mh=0;grp.forEach(function(n){var s=realSize(n);n.w=s.w;n.h=s.h;if(s.w>mw)mw=s.w;if(s.h>mh)mh=s.h;});var cw=mw+GUT,ch=mh+GUT,cc=Math.min(Math.max(grp.length,1),cols);grp.forEach(function(n,i){var r=Math.floor(i/cc),c=i%cc;n.x=Math.round(ox+c*cw+(cw-n.w)/2);n.y=Math.round(cursorY+r*ch+(ch-n.h)/2);});var rows=Math.ceil(grp.length/cc);cursorY+=rows*ch+(gi<groups.length-1?kindGap:0);});return cursorY;}
var usedSet={};S.doc.edges.forEach(function(e){if(nodeById(e.from))usedSet[e.from]=1;if(nodeById(e.to))usedSet[e.to]=1;});var used=[],unused=[];S.doc.nodes.forEach(function(n){(usedSet[n.id]?used:unused).push(n);});function upstreamAnchors(id,seen){seen=seen||{};var res=[];if(seen[id])return res;seen[id]=1;S.doc.edges.forEach(function(e){if(e.to!==id)return;var s=nodeById(e.from);if(!s)return;if(isInput(s))res.push(s);else if(isGen(s))res=res.concat(upstreamAnchors(s.id,seen));});return res;}
var adj={};used.forEach(function(n){adj[n.id]=[];});S.doc.edges.forEach(function(e){if(usedSet[e.from]&&usedSet[e.to]&&adj[e.from]&&adj[e.to]){adj[e.from].push(e.to);adj[e.to].push(e.from);}});var seenG={},groups=[];used.forEach(function(n){if(seenG[n.id])return;var stack=[n.id],comp=[];seenG[n.id]=1;while(stack.length){var cur=stack.pop();comp.push(cur);(adj[cur]||[]).forEach(function(m){if(!seenG[m]){seenG[m]=1;stack.push(m);}});}
groups.push(comp.map(function(id){return nodeById(id);}));});function layoutGroup(grp){var gInputs=grp.filter(isInput);var gGens=grp.filter(isGen);var gAssets=gInputs.filter(isAsset);var gText=gInputs.filter(function(n){return n.type==="txt";});placeByKind(gAssets,gText,0,0,GROUP_COLS,KIND_GAP);var gInputRight=gInputs.length?Math.max.apply(null,gInputs.map(function(n){return n.x+n.w;})):0;if(gGens.length){var gg=new dagre.graphlib.Graph();gg.setGraph({rankdir:"LR",nodesep:48,ranksep:130,marginx:0,marginy:0});gg.setDefaultEdgeLabel(function(){return{};});gGens.forEach(function(n){var s=realSize(n);n.w=s.w;n.h=s.h;gg.setNode(n.id,{width:s.w,height:s.h});});S.doc.edges.forEach(function(e){var f=nodeById(e.from),t=nodeById(e.to);if(f&&t&&isGen(f)&&isGen(t)&&grp.indexOf(f)>=0&&grp.indexOf(t)>=0)gg.setEdge(e.from,e.to);});try{dagre.layout(gg);}catch(err){console.warn("dagre gen layout failed",err);}
var gxs=[];gGens.forEach(function(n){var nd=gg.node(n.id);n._gx=nd.x;n._gy=nd.y;gxs.push(nd.x);});var genMinX=Math.min.apply(null,gxs);var genMinY=Math.min.apply(null,gGens.map(function(n){return n._gy;}));gGens.forEach(function(n){n.x=n._gx-genMinX-n.w/2;n.y=n._gy-genMinY-n.h/2;});var DX=gInputRight+RGAP;gGens.forEach(function(n){n.x+=DX;});gGens.forEach(function(n){var anchors=upstreamAnchors(n.id);var cy;if(anchors.length){var sum=0;anchors.forEach(function(a){sum+=a.y+a.h/2;});cy=sum/anchors.length;}else{cy=n.y+n.h/2;}
n.y=Math.round(cy-n.h/2);});}
var gTL=grp.filter(isTL);if(gTL.length){var tlBaseX=(gGens.length?Math.max.apply(null,gGens.map(function(n){return n.x+n.w;})):gInputRight)+RGAP;var prevBottom=null;gTL.forEach(function(n){var s2=realSize(n);n.w=s2.w;n.h=s2.h;n.x=Math.round(tlBaseX);var anchors2=upstreamAnchors(n.id);var cy2;if(anchors2.length){var sum2=0;anchors2.forEach(function(a){sum2+=a.y+a.h/2;});cy2=sum2/anchors2.length;}else if(prevBottom!=null){cy2=prevBottom+GUT+n.h/2;}else{cy2=n.y+n.h/2;}
n.y=Math.round(cy2-n.h/2);prevBottom=n.y+n.h;});}
return grp;}
groups.forEach(layoutGroup);var cursorY=0;groups.forEach(function(grp){var bb=bboxOf(grp);grp.forEach(function(n){n.y+=cursorY;});cursorY+=bb.h+UGAP;});var usedBox=bboxOf(used);var uOX=0;var uOY=(usedBox.h>0)?(usedBox.y+usedBox.h+UGAP):0;var unusedAssets=unused.filter(isAsset);var unusedOthers=unused.filter(function(n){return n.type!=="asset";});var uaBottom=placeByKind(unusedAssets,null,uOX,uOY,GROUP_COLS,KIND_GAP);var uoOY=uaBottom+(unusedAssets.length?UGAP:0);placeByKind([],unusedOthers,uOX,uoOY,GROUP_COLS,KIND_GAP);saveNow();renderNodes();renderEdges();fitView();}
function addNode(type,x,y){var def=NODE_DEFS[type];pushHistory(snapshotDoc());var n={id:"n_"+Date.now().toString(36)+Math.random().toString(36).slice(2,5),type:type,x:Math.round(x),y:Math.round(y),w:def.w,h:def.h,data:{}};if(type==="video_gen"||type==="image_gen"){var _dm=(type==="video_gen")?cvFirstVideoModel():null;if(type==="image_gen"){var _im=(typeof MEDIA_MODES!=="undefined"&&MEDIA_MODES.image&&MEDIA_MODES.image.models)||[];_dm=_im.length?(_im[0].value||_im[0]):"";}
if(_dm)n.data.model=_dm;}
S.doc.nodes.push(n);S.sel=n.id;saveNow();renderNodes();renderEdges();return n;}
function uploadAsset(x,y){var inp=document.createElement("input");inp.type="file";inp.accept="image/*,audio/*,video/*";inp.onchange=function(){var f=inp.files&&inp.files[0];if(!f)return;putAssetFile(f,x,y);};inp.click();}
function putAssetFile(f,x,y){var fd=new FormData();fd.append("file",f);return fetch(API+"/api/upload",{method:"POST",body:fd}).then(function(r){return r.json();}).then(function(j){if(!j.url)throw new Error(j.error||"上传失败");var n=addNode("asset",x,y);n.data={kind:j.kind,url:j.url,name:j.name||f.name};n.w=assetNodeWidth(j.kind);saveNow();renderNodes();renderEdges();return n;}).catch(function(e){alert("上传失败："+e.message);return null;});}
function dropUploadFiles(files,wx,wy){Array.prototype.forEach.call(files,function(f,i){putAssetFile(f,wx+(i%4)*180,wy+Math.floor(i/4)*210);});}
function pickAsset(x,y){if(!window.AssetPicker){alert("资产库选择器未加载");return;}
window.AssetPicker.open({source:"library",multi:false,title:"从资产库选择素材",onPick:function(items){if(!items||!items.length)return;var it=items[0];var kind=it.type||"image";var n=addNode("asset",x,y);n.data={kind:kind,url:it.url,name:it.name||it.label||"素材"};n.w=assetNodeWidth(kind);saveNow();renderNodes();renderEdges();}});}
function arsecLabel(n){var sz=String(n.data.size||(n.type==="video_gen"?"720P":"1K")).toUpperCase();return(n.type==="video_gen")?(n.data.ratio||"16:9")+" · "+(n.data.seconds||5)+"s · "+sz:(n.data.ratio||"1:1")+" · "+sz;}
function syncArsecTx(n){var tx=document.getElementById("cvArsecTx");if(tx)tx.textContent=arsecLabel(n);}
function cvCloseArsec(){var oldp=document.getElementById("cvArsecPanel");if(oldp)oldp.remove();document.removeEventListener("mousedown",cvArsecCloser,true);}
function cvArsecCloser(e){var pp=document.getElementById("cvArsecPanel");if(pp&&!pp.contains(e.target)&&!e.target.closest("#cvArsec"))cvCloseArsec();}
function openCvArsecPanel(anchor,n){cvCloseArsec();var isVid=n.type==="video_gen";var lim=(typeof MODEL_LIMITS!=="undefined"&&MODEL_LIMITS[n.data.model])||{};var p=document.createElement("div");p.className="seg-pop arsec-panel show";p.id="cvArsecPanel";var aspects=isVid?(MEDIA_MODES.video.aspects||[]):cvImgRatios(n.data.model);var curAr=n.data.ratio||(isVid?"16:9":"1:1");var html='<div class="arsec-sec"><div class="arsec-h">画幅比例</div><div class="seg-ar-grid">'+
aspects.map(function(v){return'<div class="ar-it'+(v===curAr?" on":"")+'" data-ar="'+v+'"><span class="ar-ic">'+
(typeof arIcon==="function"?arIcon(v):esc(v))+'</span><span class="ar-lb">'+esc(v)+'</span></div>';}).join("")+'</div></div>';var lo=lim.min_seconds||4,hi=lim.max_seconds||12;var curSec=Math.max(lo,Math.min(hi,n.data.seconds||5));if(isVid){html+='<div class="arsec-sec"><div class="arsec-h">视频时长</div><div class="seg-sec-pop"><div class="sec-slider">'+'<div class="sec-track"><div class="sec-fill"></div></div><div class="sec-handle"></div>'+'<div class="sec-min">'+lo+'s</div><div class="sec-max">'+hi+'s</div><div class="sec-val">'+curSec+'s</div>'+'</div></div></div>';}
var sizes=isVid?((typeof MODEL_SIZES!=="undefined"&&MODEL_SIZES[n.data.model])||lim.sizes||["720P"]):cvImgSizes(n.data.model,n.data.ratio);var curSz=String(n.data.size||(isVid?"720P":"1K")).toUpperCase();var wantSz=sizes.map(function(x){return String(x).toUpperCase();}).indexOf(curSz)>=0?curSz:String(sizes[0]).toUpperCase();if(wantSz!==curSz){n.data.size=String(sizes[0]);curSz=wantSz;}
html+='<div class="arsec-sec"><div class="arsec-h">'+(isVid?"视频分辨率":"图片分辨率")+'</div><div class="arsec-sizes">'+
sizes.map(function(s2){return'<div class="sz'+(String(s2).toUpperCase()===curSz?" on":"")+'" data-sz="'+esc(s2)+'">'+esc(s2)+'</div>';}).join("")+'</div></div>';html+='<div class="arsec-sec"><div class="arsec-h">随机种子（可选）</div><div class="arsec-seed">'+'<input type="number" id="cvSeedInput" class="seed-input" min="0" step="1" placeholder="非专业人士默认空即可" value="'+esc(n.data.seed||"")+'">'+'<button type="button" id="cvSeedRand" class="seed-rand">随机</button></div></div>';html+='<div class="arsec-foot"><button type="button" class="arsec-done">完成</button></div>';p.innerHTML=html;document.body.appendChild(p);var r=anchor.getBoundingClientRect();var left=Math.max(8,Math.min(window.innerWidth-p.offsetWidth-10,r.left));var top=r.bottom+6;if(top+p.offsetHeight>window.innerHeight-8)top=Math.max(8,r.top-p.offsetHeight-6);p.style.left=left+"px";p.style.top=top+"px";function bindCvSz(szEl){szEl.addEventListener("click",function(ev){ev.stopPropagation();n.data.size=szEl.getAttribute("data-sz");p.querySelectorAll(".sz").forEach(function(x){x.classList.toggle("on",x===szEl);});syncArsecTx(n);saveNow();renderNodesLight();});}
function rebuildCvSizes(){var ns=cvImgSizes(n.data.model,n.data.ratio);var nsUp=ns.map(function(x){return String(x).toUpperCase();});var okSz=nsUp.indexOf(String(n.data.size||"").toUpperCase())>=0?n.data.size:ns[0];n.data.size=okSz;var box=p.querySelector(".arsec-sizes");if(!box)return;box.innerHTML=ns.map(function(s2){return'<div class="sz'+(String(s2).toUpperCase()===String(okSz).toUpperCase()?" on":"")+'" data-sz="'+esc(s2)+'">'+esc(s2)+'</div>';}).join("");box.querySelectorAll(".sz").forEach(bindCvSz);syncArsecTx(n);}
p.querySelectorAll(".ar-it").forEach(function(it){it.addEventListener("click",function(ev){ev.stopPropagation();if(n.data.ratio===it.getAttribute("data-ar"))return;n.data.ratio=it.getAttribute("data-ar");p.querySelectorAll(".ar-it").forEach(function(x){x.classList.toggle("on",x===it);});rebuildCvSizes();syncArsecTx(n);saveNow();renderNodesLight();});});if(isVid){var slider=p.querySelector(".sec-slider"),handle=p.querySelector(".sec-handle"),fillEl=p.querySelector(".sec-fill"),valEl=p.querySelector(".sec-val");var snapV=function(v){var best=lo,bd=Math.abs(v-best);for(var s3=lo;s3<=hi;s3++){var d=Math.abs(v-s3);if(d<bd){best=s3;bd=d;}}return best;};var setSec=function(v){v=Math.max(lo,Math.min(hi,snapV(v)));n.data.seconds=v;var pct=(v-lo)/(hi-lo)*100;handle.style.left=pct+"%";fillEl.style.width=pct+"%";valEl.textContent=v+"s";syncArsecTx(n);};var onDown=function(downE){var track=slider.querySelector(".sec-track");var tr=track.getBoundingClientRect();var move=function(ev){setSec(lo+Math.max(0,Math.min(1,(ev.clientX-tr.left)/tr.width))*(hi-lo));};var up2=function(){document.removeEventListener("mousemove",move);document.removeEventListener("mouseup",up2);saveNow();renderNodesLight();};document.addEventListener("mousemove",move);document.addEventListener("mouseup",up2);move(downE);};handle.addEventListener("mousedown",function(e2){e2.stopPropagation();e2.preventDefault();onDown(e2);});var pct0=(curSec-lo)/(hi-lo)*100;handle.style.left=pct0+"%";fillEl.style.width=pct0+"%";}
p.querySelectorAll(".sz").forEach(bindCvSz);var seedIn=p.querySelector("#cvSeedInput");if(seedIn){seedIn.addEventListener("input",function(){n.data.seed=seedIn.value.trim();saveNow();});p.querySelector("#cvSeedRand").addEventListener("click",function(){seedIn.value=String(Math.floor(Math.random()*2147483647));n.data.seed=seedIn.value;saveNow();});}
p.querySelector(".arsec-done").addEventListener("click",function(){cvCloseArsec();});setTimeout(function(){document.addEventListener("mousedown",cvArsecCloser,true);},0);}
function addAssetNodeLinked(n,url,kind,name){if(refLocked(n)){alert(LOCKED_REF_MSG);return null;}
var aw=assetNodeWidth(kind);var a={id:"n_"+Date.now().toString(36)+Math.random().toString(36).slice(2,5),type:"asset",x:Math.round(n.x+n.w+60),y:Math.round(n.y),w:aw,h:NODE_DEFS.asset.h,data:{kind:kind,url:url,name:name||"素材"}};S.doc.nodes.push(a);var why=edgeReject(a,n);if(why){alert("素材已加入画布，但未自动连线："+why);}
else S.doc.edges.push({id:"e_"+Date.now().toString(36)+Math.random().toString(36).slice(2,5),from:a.id,to:n.id,kind:edgeKind(a,n)});saveNow();renderNodes();renderEdges();renderPanel();return a;}
function uploadIntoNode(n){var inp=document.createElement("input");inp.type="file";inp.accept="image/*,audio/*,video/*";inp.onchange=function(){var f=inp.files&&inp.files[0];if(!f)return;var fd=new FormData();fd.append("file",f);fetch(API+"/api/upload",{method:"POST",body:fd}).then(function(r){return r.json();}).then(function(j){if(!j.url)throw new Error(j.error||"上传失败");addAssetNodeLinked(n,j.url,j.kind,j.name||f.name);}).catch(function(e){alert("上传失败："+e.message);});};inp.click();}
function cvAtItems(n){var allowKinds=(n.type==="image_gen")?["image"]:["image","audio","video"];var slots=cvRefSlots(n.id);var CNtag={image:"图",audio:"音",video:"视"};return slots.queue.filter(function(a){return a.url&&allowKinds.indexOf(a.kind)>=0&&slots.numOf[a.url];}).map(function(a){var N=slots.numOf[a.url];var label=CNtag[a.kind]+N;return{id:a.nodeId,url:a.url,kind:a.kind,num:N,label:label,name:a.name||label};});}
function cvHideAtPop(){var pop=document.getElementById("cvAtPop");if(pop)pop.remove();document.removeEventListener("mousedown",cvAtCloser,true);}
function cvAtCloser(e){var pop=document.getElementById("cvAtPop");if(pop&&!pop.contains(e.target)&&!e.target.closest("#cvp_atChip"))cvHideAtPop();}
function cvAtPop(anchor,n,opts){cvHideAtPop();var items=cvAtItems(n);var pop=document.createElement("div");pop.className="at-pop show";pop.id="cvAtPop";var rows=items.map(function(it){var ic=it.kind==="image"?'<img src="'+esc(_thumb(it.url,128))+'" alt="">':'<span class="ic '+(it.kind==="audio"?"ic-audio":"ic-video")+'"></span>';return'<div class="it" data-aid="'+it.id+'"><span class="ic">'+ic+'</span><span>'+esc(it.name)+'</span><span class="lb">'+esc(it.label)+'</span></div>';}).join("");pop.innerHTML='<div class="at-hd">'+(items.length?"选择素材插入（"+items.length+"）":"暂无可引用素材")+'</div>'+
(items.length?rows:'<div class="at-empty"><span>还没有连线到本节点的素材——把素材节点连线过来（或用面板「＋」上传），连线后即可 @ 引用</span></div>');document.body.appendChild(pop);var x=anchor.x,y=anchor.y+4;if(x+pop.offsetWidth>window.innerWidth)x=window.innerWidth-pop.offsetWidth-8;if(y+pop.offsetHeight>window.innerHeight)y=Math.max(8,anchor.y-pop.offsetHeight-6);pop.style.left=Math.max(8,x)+"px";pop.style.top=Math.max(8,y)+"px";pop.querySelectorAll(".it").forEach(function(row){row.addEventListener("mousedown",function(e){e.preventDefault();});row.addEventListener("click",function(){var it=items.filter(function(x){return x.id===row.getAttribute("data-aid");})[0];if(!it)return;var ed=document.getElementById("cvp_prompt");if(ed){if(opts&&opts.typed){cvRestoreCaret(ed);cvDeleteCaretAt(ed);}
else{ed.focus();cvSaveCaret(ed);}
cvInsertAssetChip(ed,it);n.data.prompt=cvInnerTextNoChips(ed);n.data.promptTokens=cvSerializeInput(ed);}
cvHideAtPop();saveNow();});});setTimeout(function(){document.addEventListener("mousedown",cvAtCloser,true);},0);}
function cvOnPromptInput(ed,n){var pop=document.getElementById("cvAtPop");if(pop){if(!cvCaretHasAt(ed))cvHideAtPop();return;}
if(!cvCaretHasAt(ed))return;cvAtPop(cvCaretAnchor(ed),n,{typed:true});}
function cvSaveCaret(ed){var s=window.getSelection();if(s&&s.rangeCount&&ed.contains(s.anchorNode))ed._caret=s.getRangeAt(0).cloneRange();}
function cvRestoreCaret(ed){if(!ed._caret)return;var sel=window.getSelection();sel.removeAllRanges();sel.addRange(ed._caret);}
function cvDeleteCaretAt(ed){var sel=window.getSelection();if(!sel||!sel.rangeCount)return;var range=sel.getRangeAt(0);if(!range.collapsed||!ed.contains(range.startContainer))return;var node=range.startContainer;if(node.nodeType!==3)return;var off=range.startOffset;if(off<1||node.textContent[off-1]!=="@")return;var r=document.createRange();r.setStart(node,off-1);r.setEnd(node,off);r.deleteContents();range.setStart(node,Math.max(0,off-1));range.collapse(true);sel.removeAllRanges();sel.addRange(range);}
function cvCaretAnchor(ed){var range=null;var sel=window.getSelection();if(sel&&sel.rangeCount&&sel.getRangeAt(0).collapsed&&ed.contains(sel.getRangeAt(0).startContainer))range=sel.getRangeAt(0);else if(ed._caret)range=ed._caret;if(range){var r=range.getBoundingClientRect();if(r.top||r.left)return{x:r.left,y:r.bottom};}
var cr=ed.getBoundingClientRect();return{x:cr.left,y:cr.top+24};}
function cvCaretHasAt(ed){var sel=window.getSelection();if(!sel||!sel.rangeCount||!ed.contains(sel.anchorNode))return false;var r=sel.getRangeAt(0);if(!r.collapsed)return false;var sc=r.startContainer,so=r.startOffset;if(sc.nodeType===3)return/@$/.test(sc.textContent.slice(0,so))&&!/@@$/.test(sc.textContent.slice(0,so));if(so>0){var prev=sc.childNodes[so-1];return!!(prev&&prev.nodeType===3&&/@$/.test(prev.textContent)&&!/@@$/.test(prev.textContent));}
return false;}
function cvBuildChipDom(it){var wrap=document.createElement("span");wrap.className="in-asset"+(it.kind==="audio"?" audio-asset":(it.kind==="video"?" video-asset":""));wrap.contentEditable="false";wrap.dataset.url=it.url;wrap.dataset.name=it.name||"";if(it.num!=null){if(it.kind==="audio")wrap.dataset.audNum=String(it.num);else if(it.kind==="video")wrap.dataset.vidNum=String(it.num);else wrap.dataset.imgNum=String(it.num);}
if(it.kind==="image"){var img=document.createElement("img");img.className="in-img";img.src=_thumb(it.url,128);img.title=it.name||"";var lab=document.createElement("span");lab.className="in-name";lab.textContent=it.name||"";wrap.appendChild(img);wrap.appendChild(lab);}else if(it.kind==="audio"){wrap.innerHTML='<span class="in-ic ic ic-audio"></span><canvas class="in-wave" width="44" height="14"></canvas><span class="in-name">'+esc(it.name||"")+'</span>';if(window.Wave)window.Wave.mountStatic(wrap.querySelector(".in-wave"),it.url);}else{wrap.innerHTML='<span class="in-ic ic ic-video"></span><span class="in-name">'+esc(it.name||"")+'</span>';}
return wrap;}
function cvInsertAssetChip(ed,it){var wrap=cvBuildChipDom(it);var sel=window.getSelection();if(sel&&sel.rangeCount&&ed.contains(sel.anchorNode)){var range=sel.getRangeAt(0);range.deleteContents();range.insertNode(wrap);var sp=document.createTextNode(" ");wrap.after(sp);range.setStartAfter(sp);range.collapse(true);sel.removeAllRanges();sel.addRange(range);}else{ed.appendChild(wrap);ed.appendChild(document.createTextNode(" "));}}
function cvSerializeInput(ed){var tokens=[];(function walk(node){node.childNodes.forEach(function(ch){if(ch.nodeType===3){if(ch.textContent)tokens.push({t:"text",v:ch.textContent});}
else if(ch.nodeType===1){var cls=ch.classList||{};if(cls.contains&&cls.contains("in-asset")){var kind=cls.contains("audio-asset")?"audio":(cls.contains("video-asset")?"video":"image");var numAttr=kind==="audio"?ch.dataset.audNum:(kind==="video"?ch.dataset.vidNum:ch.dataset.imgNum);tokens.push({t:kind,url:ch.dataset.url||"",name:ch.dataset.name||"",num:numAttr?parseInt(numAttr,10):null});return;}
if(ch.tagName==="BR"){tokens.push({t:"br"});return;}
walk(ch);}});})(ed);return tokens;}
function cvReconstructFromTokens(ed,tokens,nid){ed.innerHTML="";var frag=document.createDocumentFragment();var slots=nid?cvRefSlots(nid):null;(tokens||[]).forEach(function(tk){if(tk.t==="text"){if(tk.v)frag.appendChild(document.createTextNode(tk.v));}
else if(tk.t==="br"){frag.appendChild(document.createElement("br"));}
else{var num=slots?(slots.numOf[tk.url]||null):(tk.num==null?null:tk.num);frag.appendChild(cvBuildChipDom({kind:tk.t,url:tk.url,name:tk.name,num:num}));frag.appendChild(document.createTextNode(" "));}});ed.appendChild(frag);}
function cvInnerTextNoChips(ed){var out="";(function walk(node){node.childNodes.forEach(function(ch){if(ch.nodeType===3)out+=ch.textContent;else if(ch.nodeType===1&&!(ch.classList&&ch.classList.contains("in-asset")))walk(ch);});})(ed);return out.replace(/\u00a0/g," ");}
function fillCvStrip(n,root){var strip=(root||document).querySelector("#cvp_ustrip");if(!strip)return;var slots=cvRefSlots(n.id);var CNtag={image:"图",audio:"音",video:"视"};strip.innerHTML=slots.queue.map(function(a){var isAu=a.kind==="audio",isVid=a.kind==="video";var N=slots.numOf[a.url];var dropped=!N;var tagTxt=dropped?"超限":(CNtag[a.kind]+N);return'<div class="uth'+(isAu?" audio":(isVid?" video":""))+(dropped?" cv-dropped":"")+'"'+
(dropped?' title="'+esc(a.name||"")+'（超出该模型参考上限，不会随请求发出）"':' title="'+esc(a.name||"")+'（单击预览）"')+' data-cv-chip="1"'+' data-cv-kind="'+(isAu?"audio":(isVid?"video":"image"))+'" data-cv-url="'+esc(a.url)+'"'+' data-cv-name="'+esc(a.name||"")+'" data-cv-tag="'+esc(tagTxt)+'">'+
(isAu?'<div><span class="ic ic-audio"></span></div>':(isVid?'<div><span class="ic ic-video"></span></div>':'<img src="'+esc(_thumb(a.url,128))+'" alt="">'))+'<span class="tag">'+tagTxt+'</span>'+'<button class="x" data-qdel="'+esc(a.edgeId)+'" title="移除引用（素材节点保留）"><span class="ic ic-cancel"></span></button></div>';}).join("");strip.querySelectorAll("[data-qdel]").forEach(function(x){x.addEventListener("click",function(ev){ev.stopPropagation();var eid=x.getAttribute("data-qdel");S.doc.edges=S.doc.edges.filter(function(e){return e.id!==eid;});saveNow();renderNodes();renderEdges();});});if(!strip.__cvPreviewBound){strip.__cvPreviewBound=true;strip.addEventListener("click",function(ev){if(ev.target.closest&&ev.target.closest("[data-qdel]"))return;var chip=ev.target.closest&&ev.target.closest("[data-cv-chip]");if(!chip||!strip.contains(chip))return;var kind=chip.getAttribute("data-cv-kind");var url=chip.getAttribute("data-cv-url");var name=chip.getAttribute("data-cv-name")||"";if(kind==="image"){var list=slots.images.filter(Boolean);if(typeof openLightbox==="function")openLightbox(list,list.indexOf(url),name);else if(window.openMediaPreview)window.openMediaPreview({url:url,type:"image",name:name,category:"画布素材列队"});return;}
if(!window.openMediaPreview)return;window.openMediaPreview({url:url,type:kind==="video"?"video":"audio",name:name,category:"画布素材列队"+(chip.getAttribute("data-cv-tag")?" · "+chip.getAttribute("data-cv-tag"):"")});});}}
function cvUpPop(anchor,n){var old=document.getElementById("cvUpPop");if(old)old.remove();var pop=document.createElement("div");pop.className="seg-pop show";pop.id="cvUpPop";pop.innerHTML='<div class="seg-it" data-up="local"><span class="ic ic-upload"></span>从本地上传</div>'+'<div class="seg-it" data-up="lib"><span class="ic ic-library"></span>从资产库上传</div>';document.body.appendChild(pop);var r=anchor.getBoundingClientRect();pop.style.left=Math.max(8,r.left)+"px";pop.style.top=Math.min(window.innerHeight-120,r.bottom+6)+"px";pop.addEventListener("click",function(e){var it=e.target.closest(".seg-it");if(!it)return;pop.remove();if(it.getAttribute("data-up")==="local")uploadIntoNode(n);else{if(!window.AssetPicker){alert("资产库选择器未加载");return;}
window.AssetPicker.open({source:"library",multi:false,title:"从资产库选择素材",onPick:function(items){if(!items||!items.length)return;var it2=items[0];addAssetNodeLinked(n,it2.url,it2.type||"image",it2.name||it2.label||"素材");}});}});setTimeout(function(){var closer=function(e){if(!e.target.closest("#cvUpPop")&&!e.target.closest("#cvp_upIconBtn")){pop.remove();document.removeEventListener("mousedown",closer,true);}};document.addEventListener("mousedown",closer,true);},0);}
function drawLinkGhost(){var svg=document.getElementById("csEdges");if(!svg||!S.linking)return;removeLinkGhost();var p=document.createElementNS("http://www.w3.org/2000/svg","path");p.id="csLinkGhost";p.setAttribute("d","M"+S.linking.x+" "+S.linking.y+" C "+(S.linking.x+40)+" "+S.linking.y+", "+(S.linking.mx-40)+" "+S.linking.my+", "+S.linking.mx+" "+S.linking.my);p.setAttribute("stroke","#7c3aed");p.setAttribute("stroke-width","2.5");p.setAttribute("stroke-linecap","round");p.setAttribute("fill","none");p.setAttribute("stroke-dasharray","5 4");svg.appendChild(p);}
function removeLinkGhost(){var g=document.getElementById("csLinkGhost");if(g)g.remove();}
document.addEventListener("keydown",function(e){if(e.key==="Escape"){if(document.getElementById("csCtx")){closeCtxMenu();return;}
if(S.doc)closeStage();}});document.addEventListener("keydown",function(e){if(!(e.ctrlKey||e.metaKey))return;var k=(e.key||"").toLowerCase();if(k!=="z"&&k!=="y")return;if(!S.doc)return;var t=e.target;if(t&&(t.tagName==="TEXTAREA"||t.tagName==="INPUT"||t.isContentEditable))return;e.preventDefault();if(k==="z"&&e.shiftKey)redo();else if(k==="z")undo();else if(k==="y")redo();});document.addEventListener("keydown",function(e){if(!(e.ctrlKey||e.metaKey))return;var k=(e.key||"").toLowerCase();if(k!=="c"&&k!=="v")return;if(!S.doc)return;var t=e.target;if(t&&(t.tagName==="TEXTAREA"||t.tagName==="INPUT"||t.isContentEditable))return;var ids=(S.selSet&&S.selSet.length)?S.selSet.slice():(S.sel?[S.sel]:[]);if(k==="c"){if(!ids.length)return;e.preventDefault();copyNodes(ids);}else if(k==="v"){if(!S.clipboard)return;e.preventDefault();var work=document.getElementById("csWork");var wr=work.getBoundingClientRect();var wx=(wr.width/2-S.vp.x)/S.vp.zoom;var wy=(wr.height/2-S.vp.y)/S.vp.zoom;pasteNodes(wx,wy);}});function bindTextHistory(){var work=document.getElementById("csWork");if(!work)return;work.addEventListener("focusin",function(e){var ta=e.target.closest&&e.target.closest("[data-txt]");if(!ta)return;S._txtSnap=snapshotDoc();S._txtNode=ta.getAttribute("data-txt");var nn=S.doc.nodes.filter(function(n){return n.id===S._txtNode;})[0];S._txtVal=nn?(nn.data.text||""):"";});work.addEventListener("focusout",function(e){var ta=e.target.closest&&e.target.closest("[data-txt]");if(!ta||!S._txtSnap)return;var n=S.doc.nodes.filter(function(n){return n.id===S._txtNode;})[0];var now=n?(n.data.text||""):"";if(now!==S._txtVal)pushHistory(S._txtSnap);S._txtSnap=null;S._txtNode=null;S._txtVal=null;});}
document.addEventListener("keydown",function(e){if(e.key!=="Delete"&&e.key!=="Backspace")return;if(!S.doc)return;var t=e.target;if(t&&(t.tagName==="TEXTAREA"||t.tagName==="INPUT"||(t.isContentEditable)))return;var ids=(S.selSet&&S.selSet.length)?S.selSet.slice():(S.sel?[S.sel]:[]);if(!ids.length)return;e.preventDefault();deleteNodes(ids);});window.CANVAS_STAGE={openProject:openProject,close:closeStage};})();